### ISSUE TITLE
[BUG] MacOS上安装后，依旧无法输入中文

### ISSUE THREAD

**Issue by Tubo** [DogLooksGood/emacs-rime#102]
**问题描述**

MacOS上安装后，依旧无法输入中文，除了modeline的图标外，和没安装没有区别，也没有任何报错。
Emacs 版本为 @railwaycat 的brew版本，也编译了dynamic module。

**Emacs中的配置**

```
(use-package rime
  :straight (rime :type git
                  :host github
                  :repo "DogLooksGood/emacs-rime"
                  :files ("*.el" "Makefile" "lib.c"))
  :custom
  (rime-librime-root "~/.emacs.d/rime-1.5.3-osx/dist")
  (rime-user-data-dir "~/.emacs.d/config/rime")
  (default-input-method "rime")
  (rime-show-candidate 'minibuffer)
  :general
  (:keymaps 'rime-mode-map
            "C-`" 'rime-send-keybinding))
```

**复现方式**（安装遇到问题时省略）

正常输入任何字。

**是否可在 emacs -Q 中复现**

可以。

**截图**

![image](https://user-images.githubusercontent.com/7521921/85946590-8aeacd00-b999-11ea-9bce-0ab34b95eb89.jpeg)

**环境信息**

- 操作系统：MacOS Catalina
- Emacs版本：如 26.3 
- Librime版本：如 1.5.3
- Librime安装方式：来自github的osx的binary
- 安装方式：Straight

**Comment by DogLooksGood** [comment]
我猜测你的 rime 配置默认为英文。 "C-`" 用这个把菜单呼出来看一下？

**Comment by Tubo** [comment]
> 我猜测你的 rime 配置默认为英文。 "C-`" 用这个把菜单呼出来看一下？

恩，试过了，木有反应。

**Comment by DogLooksGood** [comment]
如果你用 rime-comiple-module 会有什么反应？

**Comment by Tubo** [comment]
已经修好了，原来是因为我没有安装Squirrel，以至于没有输入法的schema。
建议在文档中加入这一点，以方便Rime新手和太久没用过的人。
若不介意，我可以做个pull request。

**Comment by DogLooksGood** [comment]
好的，非常感谢，我觉得在合适的位置加一句话的注明应该就可以。

**Comment by Grant-S-Z** [comment]
> 我猜测你的 rime 配置默认为英文。 "C-`" 用这个把菜单呼出来看一下？

您好，我系统中 Squirrel 默认为英文，因而在 Emacs 中无法输入中文，修改默认后解决了。有没有办法在不修改系统默认的情况下在 Emacs 中使用 emacs-rime 正常输入中文呢？
