### ISSUE TITLE
请问支援 lua 吗？

### ISSUE THREAD

**Issue by lyserenity** [DogLooksGood/emacs-rime#105]
鼠须管已经支援 lua 了，请问 emacs-rim 是不是还不行？还是需要做什么配置？谢谢

**Comment by DogLooksGood** [comment]
我没有用过lua来扩展rime，这是鼠须管特有的功能还是rime的功能？

**Comment by lyserenity** [comment]
应该是 rime 的，同文/小狼毫/鼠须管新版的基本都支持，在这：
https://github.com/hchunhui/librime-lua

我主要是用来快速输入日期和时间.....

**Comment by DogLooksGood** [comment]
原来如此。

我觉得你可以试用 elisp 直接实现这些效果，虽然输入方式可能不同。
从这个项目来看，似乎是要在构建 librime 上面来添加这个 plugin，这应该不在这个项目的范畴中。

**Comment by lyserenity** [comment]
当然还是有很多功能，不过没关系，还是谢谢你！

**Comment by ginqi7** [comment]
![image](https://user-images.githubusercontent.com/1028971/205220829-bda20b41-d764-4606-94b7-51d650d1f281.png)
Windows 和 Mac 用户，直接下载 with-plugins librime 就可以直接使用 lua 脚本功能。
如果是 Linux 用户可能需要自己编译 librime

**Comment by ginqi7** [comment]
> > ![image](https://user-images.githubusercontent.com/1028971/205220829-bda20b41-d764-4606-94b7-51d650d1f281.png) Windows 和 Mac 用户，直接下载 with-plugins librime 就可以直接使用 lua 脚本功能。 如果是 Linux 用户可能需要自己编译 librime
> 
> 我是 mac 用戶。 抱歉，因为我是个小白，能不能详细说一下下载解压后我应该放到哪里，好让 emacs-rime 可以适用，感谢大佬！

解压后放置在任何位置，在 emacs 中设置变量，例如我自己，解压为：~/.emacs.d/librime：
```
rime-user-data-dir "~/Library/Rime"
rime-librime-root "~/.emacs.d/librime/dist"
```

**Comment by lyserenity** [comment]
@ginqi7 
<img width="933" alt="image" src="https://github.com/DogLooksGood/emacs-rime/assets/32646062/b60b15b4-2522-4bd2-9722-89b5e6060464">

不好意思，想请问下对于 1.8.5 ，我是该下载哪一个呢？是 ``rime-deps-08dd95f-macOS.tar.bz2`` 吗？
谢谢！

**Comment by roife** [comment]
@lyserenity 都下载，其中第一个是 rime，第二个是这些依赖，把他们解压到一个文件夹就好了

**Comment by lyserenity** [comment]
> @lyserenity 都下载，其中第一个是 rime，第二个是这些依赖，把他们解压到一个文件夹就好了

成功了，非常感谢大佬，原来是这样做的，太开心了！

**Comment by roife** [comment]
@DogLooksGood 我认为是不是最好在安装文档中提一下这一点，即部分 lua 相关的功能可能需要安装 librime-lua 才能使用
