### ISSUE TITLE
[BUG] 使用posframe显示候选词时，第九个候选不显示

### ISSUE THREAD

**Issue by VitalyAnkh** [DogLooksGood/emacs-rime#106]
**问题描述**

如题

**Emacs中的配置**

```
(setq default-input-method "rime")
(setq rime-user-data-dir "~/sdk/config/input_method/rime")
(setq rime-show-candidate 'posframe)
(setq rime-disable-predicates
      '(rime-predicate-evil-mode-p
        rime-predicate-after-alphabet-char-p
        rime-predicate-prog-in-code-p
        ))
;; (setq rime-posframe-properties
;;  (list :font "sarasa ui sc"
;;        :internal-border-width 10))
(setq rime--popup 1)
(setq rime-show-preedit 1)
;;(setq rime-posframe-fixed-position t)
```

**复现方式**（安装遇到问题时省略）

我使用doom-emacs，在doom-emacs的`package.el`中指定安装github仓库的emacs-rime，使用上面的配置，就会出现这个问题

**是否可在 emacs -Q 中复现**

我不知道如何在emacs -Q 中使用emacs-rime :sweat_smile: 

**截图**
![image](https://user-images.githubusercontent.com/24508452/86269538-78bc9900-bbfc-11ea-896e-b2b04b9e8160.png)

**环境信息**

- 操作系统：ArchLinux
- Emacs版本：28.0.50
- Librime版本：1.5.3
- Librime安装方式：包管理器
- 安装方式：Git

**Comment by VitalyAnkh** [comment]
噢，是老问题了 https://emacs-china.org/t/posframe/12250/7

**Comment by cnsunyour** [comment]
请细读README，FAQ 有解。

**Comment by VitalyAnkh** [comment]
@cnsunyour 看到了！但这的确是一个bug，让这个issue开着吧

**Comment by cnsunyour** [comment]
> @cnsunyour 看到了！但这的确是一个bug，让这个issue开着吧

但是在这里开着 issue 解决不了，我之前向 posframe 提过一个 issue https://github.com/tumashu/posframe/issues/59 ，不过定位原因似乎比较困难。

**Comment by DogLooksGood** [comment]
一个办法是某些字体没有这样的问题，另一个办法就是 FAQ 里面的办法。
