### ISSUE TITLE
[BUG] 输入过的短语不会被记住

### ISSUE THREAD

**Issue by rwszh1** [DogLooksGood/emacs-rime#107]
**问题描述**

输入过的短语不会被记住

**Emacs中的配置**

```
(require 'rime)
(setq rime-user-data-dir "~/.config/fcitx/rime")
(setq default-input-method "rime"
      rime-show-candiate 'posframe)
```

**复现方式**

在 emacs 中按 C-\ 启动 rime，然后随意输入一个不常见（需要选择）的短语，之后再重新输入一次

**是否可在 emacs -Q 中复现**

是

**截图**
![Screenshot_2020-07-06_18-04-50](https://user-images.githubusercontent.com/66938949/86570946-1248c980-bfb4-11ea-9dbc-a914b70afad2.png)

**环境信息**

- 操作系统：Debian 10
- Emacs版本：27.0.91
- Librime版本：1.4.0+dfsg1-2+b1
- Librime安装方式：包管理器
- 安装方式：Melpa

**Comment by Z572** [comment]
rime-user-data-dir 不能设置和系统 rime 一样，会冲突，可以使用软链接链到其他文件夹再设置 rime-user-data-dir 为那个目录



---原始邮件---
发件人: "rwszh1"<notifications@github.com&gt;
发送时间: 2020年7月6日(周一) 下午4:11
收件人: "DogLooksGood/emacs-rime"<emacs-rime@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [DogLooksGood/emacs-rime] [BUG] 输入过的短语不会被记住 (#107)




 
问题描述
 
输入过的短语不会被记住
 
Emacs中的配置
 (require 'rime) (setq rime-user-data-dir "~/.config/fcitx/rime") (setq default-input-method "rime"       rime-show-candiate 'posframe)  
复现方式
 
在 emacs 中按 C-\ 启动 rime，然后随意输入一个不常见（需要选择）的短语，之后再重新输入一次
 
是否可在 emacs -Q 中复现
 
是
 
截图
 
 
环境信息
  
操作系统：Debian 10 

Emacs版本：27.0.91 

Librime版本：1.4.0+dfsg1-2+b1 

Librime安装方式：包管理器 

安装方式：Melpa
