### ISSUE TITLE
只能一个字一个字地打怎么办

### ISSUE THREAD

**Issue by nesteiner** [DogLooksGood/emacs-rime#112]
![x](https://user-images.githubusercontent.com/46296608/88447043-cde97480-ce61-11ea-9aba-951534a46136.gif)

**Comment by Z572** [comment]
你这不是 emacs-rime 啊

**Comment by nesteiner** [comment]
???
我在melpa里装的`emacs-rime`啊

**Comment by cnsunyour** [comment]
他是想对比两个输入法的差别，系统输入法能打词组，emacs-rime不能。话说兄台发 issue 能不能加点说明啊，发个动图让人猜么？

2020-07-25 10:48 GMT+08:00, nesteiner <notifications@github.com>:

**Comment by Z572** [comment]
他用的不是 emacs 的默认输入法吗?

**Comment by Z572** [comment]
应该设置
``` lisp
(setq default-input-method "rime")
```
才用的 emacs-rime 啊

**Comment by nesteiner** [comment]
我去，谢谢，
不过我好像又遇到问题了，激活的时候提醒我
`Compile Rime dynamic module failed`
我该怎么办？？

**Comment by cnsunyour** [comment]
还是你细心

Z572 <notifications@github.com> 于2020年7月25日周六 上午10:52写道：

**Comment by DogLooksGood** [comment]
emacs-china 的贴子里看到了你提的问题，ubuntu 的源的 librime 版本太老，需要自己编译。
