### ISSUE TITLE
[BUG] 在输入过程中，候选被意外关闭

### ISSUE THREAD

**Issue by wolongge** [DogLooksGood/emacs-rime#114]
**问题描述**
我使用的是键道6输入方案，比如我输入 ”ejrj“ 再输入 "n"，中间不敲空格，前两个字会上屏，并且 ”n“ 所输入的后续会继续拼写出 ”你“ 字。

而我现在输入 "ejrjn" 只会打上两个字”输入“，”n“相当于空格了。

比直接用 rime 输入法，要多敲一个空格。

**简明的问题描述**
输入体验与 rime 输入法不一致。

**Emacs中的配置**

```
(use-package! rime
  :custom
  (default-input-method "rime"))
(setq rime-show-candidate 'posframe)
(setq! rime-posframe-style 'vertical)
```

**复现方式**（安装遇到问题时省略）

复现问题所需的操作

**是否可在 emacs -Q 中复现**

**截图**

展示错误的截图或动图

两次都是输入："ejrjn"
![Peek 2020-09-10 22-58](https://user-images.githubusercontent.com/32229530/92750141-6065b900-f3b9-11ea-8331-b911fe195ba5.gif)

**环境信息**

- 操作系统：Ubuntu 20.04
- Emacs版本：27.1
- Librime版本：1.5.3 (librime-dev)
- Librime安装方式：apt
- 安装方式：doom emacs （应该是 Straight）

**Comment by DogLooksGood** [comment]
应该是上次改动引入的一个bug，马上就可以修复好

**Comment by DogLooksGood** [comment]
在最新的版本中尝试修复了这个问题。

**Comment by wolongge** [comment]
嗯，好了，谢谢，以后可以在 emacs 里有预览了，真棒。

> doom-emacs 各种搞都不重新下载包，把本地的文件删掉才重新下载，又搞了好久。。。。。

**Comment by wolongge** [comment]
额，还是有问题，我试用的时候是在 config.el 里玩的，然后到了 Org 里还是不行，这就很要命了，打文档的时候还是老样子。

**Comment by DogLooksGood** [comment]
不应该有这样的情况的，因为不管是输入法，还是 emacs-rime 本身对 org 模式还是编程的模式都是没有区分的。

**Comment by DogLooksGood** [comment]
不好意思，我好像知道问题了。

**Comment by DogLooksGood** [comment]
最新的 master 分支修复了这个问题。

这个问题的原因在于，为了让使用其它命令的时候，可以自动的关闭候选，emacs-rime 选择了在当前命令是 rime- 无关，或 self-insert-command  的情况下退出输入状态。

但是 org-mode 里面这个命令叫 org-self-insert-command，暂时只能尝试匹配所有包含 self-insert 的命令。

**Comment by wolongge** [comment]
辛苦！Org 里也好了。

有个小问题，每次启动输入法，Emacs 会重置我鼠标的位置，将我鼠标给移到左上角，不确定是不是 emacs-rime 引起的。

**Comment by DogLooksGood** [comment]
这个应该是第一次启动的时候，创建 posframe 时的问题。这里 emacs-rime 似乎没有什么可做的。
