### ISSUE TITLE
[FETURE] 添加本次 rime 启动后输入速度、时间和字数统计

### ISSUE THREAD

**Issue by fpGHwd** [DogLooksGood/emacs-rime#119]
在使用 fcitx-rime 有显示输入速度的一项设置，能在激活 fcitx-rime 的时候显示（自本次 rime 启动开始的）输入的平均速度、时间和字数的统计。这个功能还蛮好的。希望可以添加到 emcs-rime 的接口中。

由于这个数据显示只有2秒大概，截图有点困难，[用了一个 webm 文件记录了一下](https://raw.githubusercontent.com/fpGHwd/shared-files/master/Peek%202020-10-30%2010-19.webm)。

Many thanks~

**Comment by DogLooksGood** [comment]
感谢这个建议！

但是 emacs-rime 并不会添加这个功能。这个项目意在提供 rime 所据有的功能，和解决 rime 集成 emacs 输入法接口带来的缺陷。而输入统计我理解是 fcitx 的一个功能。所以我不认为应该进行这类的扩展。

不过，从这个需求来看，是可以不修改 emacs-rime 就实现的。只需要在 rime-input-method 这个函数添加 advice，就可以完成输入速度和字数的统计。

**Comment by fpGHwd** [comment]
好的谢谢
