### ISSUE TITLE
Why do you create this project, considering that there are already several popular frontends for rime?

### ISSUE THREAD

**Issue by hongyi-zhao** [DogLooksGood/emacs-rime#125]
I noticed that there are already several [frontends](https://github.com/rime/librime#frontends) available for rime, especially [ibus-rime](https://github.com/rime/ibus-rime) and [fcitx-rime](https://github.com/rime/ibus-rime). So, I want to know why you still will create this project.

Any hints will be highly appreciated.

Regards,
HY

**Comment by DogLooksGood** [comment]
Hi, There're serval reasons.

First, make rime interactable with Emacs, it's possible to let Emacs toggle ascii mode automatically.

Second, Emacs doesn't play nice with fcitx or ibus's preedit feature(embedded inline compositor).

Third, make it possible to customize how candidate window looks like with Emacs themes.

**Comment by hongyi-zhao** [comment]
If I already installed the  ibus-rime or fcitx-rime, will emacs-rime conflict with them?

**Comment by DogLooksGood** [comment]
I disable system input method in Emacs. 

Either by not setting `LC_CTYPE` to `zh_CN.UTF-8` or setting `Emacs*useXIM: false` in `~/.Xresources`.

**Comment by QiangF** [comment]
fcitx5是不是也能弄个动态模块，让emacs-rime和fcitx5-rime共用一个rime引擎？
https://github.com/fcitx/fcitx5-rime.git

**Comment by DogLooksGood** [comment]
> fcitx5是不是也能弄个动态模块，让emacs-rime和fcitx5-rime共用一个rime引擎？
> https://github.com/fcitx/fcitx5-rime.git

好像不可以，就算用了动态模块，也是两个 rime 的 app。不知道有没有办法在 emacs 里面直接接上 fcitx?

**Comment by QiangF** [comment]
@DogLooksGood 能不能用lua作为沟通fcitx和emacs的桥梁，用rpc之类的，fcitx那边用lua plugin, 用来开关fcitx，
https://www.aloxaf.com/2020/09/fcitx5_plugin/
https://github.com/syohex/emacs-lua
https://github.com/stockrt/luarpc

**Comment by QiangF** [comment]
或者直接弄个fcitx-emacs frontend
https://github.com/fcitx/fcitx/tree/master/src/frontend/xim

**Comment by DogLooksGood** [comment]
那样的话就是另一个项目的职责了，比如说 emacs-fcitx。

emacs-rime 同时还要解决在 terminal 下使用的问题（虽然现在要用 emacsclient 才能正常用）。
