### ISSUE TITLE
[Question] Why do you clone the librime source code into: ~/.emacs.d/librime?

### ISSUE THREAD

**Issue by hongyi-zhao** [DogLooksGood/emacs-rime#128]
You told the following steps in the section of [librime installation](https://github.com/DogLooksGood/emacs-rime#%E5%AE%89%E8%A3%85-librime):

```
sudo apt install git build-essential cmake libboost-all-dev libgoogle-glog-dev libleveldb-dev libmarisa-dev libopencc-dev libyaml-cpp-dev libgtest-dev
git clone https://github.com/rime/librime.git ~/.emacs.d/librime
cd ~/.emacs.d/librime
make
sudo make install
```
But I really confused on the location used by you to populate the librime source code. In more detail, you install it by `sudo make install`, which will install the librime into standard locations used by libraries, say, for my case, I observered the following results:

```
$ cat install_manifest.txt 
/usr/lib/x86_64-linux-gnu/pkgconfig/rime.pc
/usr/share/cmake/rime/RimeConfig.cmake
/usr/include/rime_api.h
/usr/include/rime_levers_api.h
/usr/lib/x86_64-linux-gnu/librime.so.1.6.1
/usr/lib/x86_64-linux-gnu/librime.so.1
/usr/lib/x86_64-linux-gnu/librime.so
/usr/bin/rime_deployer
/usr/bin/rime_dict_manager
```
Hence, there is no need to preserve the librime source code after the installation has finished. Let alone put it in a specific location used by emacs.

Any hints for your idea will be highly appreciated.

Regards,
HY

**Comment by DogLooksGood** [comment]
Hi, thank you for pointing this out! I'm not an ubuntu user. The main purpose of this section, it tell how to build librime from source code, because the version of librime in apt was too old.

But, recently, I notice in the latest ubuntu release, it's ok to install librime from apt, so probably I will update this section. 

And PR is always welcomed!

**Comment by hongyi-zhao** [comment]
Basically, for librime installation on Debian based OSes, the following should be enough:

```
git clone https://github.com/rime/librime.git librime.git
sudo apt-get build-dep -y librime
sudo apt-get install -y capnproto libcapnp-dev libgtest-dev libgoogle-glog-dev

mkdir build && cd $_
cmake ..
make -j `nproc`
sudo make install
```

**Comment by DogLooksGood** [comment]
Maybe install via apt directly is also possible. emacs-rime require a version that greater than 1.5.

**Comment by hongyi-zhao** [comment]
The above notes just deal with the case where the package in apt repo doesn't meet the requirement.
