### ISSUE TITLE
[BUG]在magit的buffer里，触发一个动作后，切换输入到rime，会导致后续无法操作

### ISSUE THREAD

**Issue by lawrsp** [DogLooksGood/emacs-rime#129]
**问题描述**

打开一个magit buffer，按i，跳出magit的命令提示，然后 `C-\` 切换

然后就再也无法操作了，看起来普通输入被rime截走了，而 `C-\` 被magit截了，导致无法再操作

**Emacs中的配置**
windows wsl2 + spacemacs + rime

```
(use-package rime
    :defer t
    :bind
    (:map rime-active-mode-map
          ("<tab>" . 'rime-inline-ascii)
          :map rime-mode-map
          ("C-`" . 'rime-send-keybinding))
    ))
```
![1](https://user-images.githubusercontent.com/7957003/101493654-52680a00-39a1-11eb-9efd-a50c89e98e35.png)
![2](https://user-images.githubusercontent.com/7957003/101493657-53993700-39a1-11eb-942a-62c1d38d5a49.png)

**Comment by lawrsp** [comment]
解决方法是，把 C-g 从发送给rime的列表里去掉
```
  (setq rime-translate-keybindings
          '("C-f" "C-b" "C-n" "C-p" "<left>" "<right>" "<up>" "<down>" "<prior>" "<next>" "<delete>"))
```

不知道不发 `C-g`  对rime有什么影响？

**Comment by cnsunyour** [comment]
我这里没有此问题，你可参考我配置里的断言函数，看有否能解决你的问题的

**Comment by lawrsp** [comment]
@cnsunyour 刚才的描述顺序有些错误，我这必现流程：

1. 打开 magit buffer （M-x  magit-status）
2. `C-\` 切换到 rime 输入法
3. 打开一个多步的命令，比如 p  ，然后会在弹出 magit的p命令的提示，
4.  `C-g`  试图取消

这个时候，就进入死锁情形.
顺序 和 最后的 `C-g` 都不可少

不太懂断言是做什么的，`C-g` 不发就没问题了

**Comment by lawrsp** [comment]
试了断言，都无效

另外建议这个 `rime-disable-predicates` 改个名字，我还以为是要disable这个列表，导致很疑惑，原来是用这个列表disable rime

**Comment by cnsunyour** [comment]
> @cnsunyour 刚才的描述顺序有些错误，我这必现流程：
> 
> 1. 打开 magit buffer （M-x  magit-status）
> 2. `C-\` 切换到 rime 输入法
> 3. 打开一个多步的命令，比如 p  ，然后会在弹出 magit的p命令的提示，
> 4. `C-g`  试图取消
> 
> 这个时候，就进入死锁情形.
> 顺序 和 最后的 `C-g` 都不可少
> 
> 不太懂断言是做什么的，`C-g` 不发就没问题了

我这里仍然无法复现。我的环境： macOS Big Sur , emacs-mac 27.1 , doom-emacs + private config .
我的私有配置里有自定义断言函数，没有在 emacs-rime 包里，你可再试一下。

**Comment by DogLooksGood** [comment]
我也是 magit 用户，从来没有在 magit buffer 切换过输入法，你们是遇到了什么场景呢？

**Comment by DogLooksGood** [comment]
在最新的 magit 下面没有办法重现这个问题，所以先关闭了。
