### ISSUE TITLE
能否像普通输入法一样，通过Shift键切换中文/西文输入模式？

### ISSUE THREAD

**Issue by wang1zhen** [DogLooksGood/emacs-rime#130]
由于可能有中西文混合输入的情景，因此希望可以简单地通过左Shift键切换中西文的输入模式（就如同windows下的输入方式一样），请问这可以实现吗？
我尝试了`(setq rime-inline-ascii-trigger 'shift-l)`似乎并没有效果。

**Comment by cnsunyour** [comment]
不能，因为 Emacs 里不能捕获单独的 Shift 键。不过可以曲线救国，就是用键盘映射软件把单独的 Shift 映射成 C-\

**Comment by yxsongbo** [comment]
具体是要怎么映射呢？

**Comment by wang1zhen** [comment]
> 具体是要怎么映射呢？

建议使用powertoys，增加一个键盘映射即可，很方便
