### ISSUE TITLE
[BUG] The input method candidate box can't follow the cursor.

### ISSUE THREAD

**Issue by hongyi-zhao** [DogLooksGood/emacs-rime#132]
When I use the eaf-open-browser command shipped in [EAF](https://github.com/manateelazycat/emacs-application-framework) to surfing the website, I find that the input method candidate box activated by emacs-rime can't follow the cursor. See the screenshot for detailed info:

![image](https://user-images.githubusercontent.com/11155854/102007158-907a7a80-3d61-11eb-8de5-26cda5346ec0.png)

As you can see, the position of the input method candidate box is fixed in the upper left corner of the screen instead of following the cursor. Any hints for solving this problem?

Regards,
HY

**Comment by DogLooksGood** [comment]
Sorry, I have no experience with EAF. 

But AFAIK, @manateelazycat also use emacs-rime,  maybe you can get help from him.

**Comment by cnsunyour** [comment]
抱歉我的英文很差，我就用中文发表下看法。我的理解是 emacs-rime 的光标跟随是基于文字模式的当前光标位置，而 eaf-browser  是调用 xwidget 进行的渲染，对于 emacs-rime 来说，无论页面如何变化，当前光标位置都是在 eaf-browser 的左上角位置不动，所以输入提示框就一直在那个位置。

**Comment by manateelazycat** [comment]
> 抱歉我的英文很差，我就用中文发表下看法。我的理解是 emacs-rime 的光标跟随是基于文字模式的当前光标位置，而 eaf-browser 是调用 xwidget 进行的渲染，对于 emacs-rime 来说，无论页面如何变化，当前光标位置都是在 eaf-browser 的左上角位置不动，所以输入提示框就一直在那个位置。

第一,EAF和xwidgets没任何半毛钱关系，第二，这个问题和emacs-rime一点关系都没有，请不要烦emacs-rime的作者

**Comment by cnsunyour** [comment]
> > 抱歉我的英文很差，我就用中文发表下看法。我的理解是 emacs-rime 的光标跟随是基于文字模式的当前光标位置，而 eaf-browser 是调用 xwidget 进行的渲染，对于 emacs-rime 来说，无论页面如何变化，当前光标位置都是在 eaf-browser 的左上角位置不动，所以输入提示框就一直在那个位置。
> 
> 第一,EAF和xwidgets没任何半毛钱关系，第二，这个问题和emacs-rime一点关系都没有，请不要烦emacs-rime的作者

第一，我观点不对是我知识不够，您愿意可以指出我的错误，我非常感谢。
第二，收到此消息是因为之前我积极参与 emacs-rime 的测试和优化所以订阅了消息提醒，因此有其它用户提出 issue 我有意愿出一把力，能不能出的上力是我的水平问题，愿不愿意出力是态度问题。不需要您气指颐使指手划脚。

**Comment by DogLooksGood** [comment]
Close for inactivate.
