### ISSUE TITLE
[BUG] IO error: lock /home/werner/.local/share/fcitx5/rime/luna_pinyin.userdb/LOCK: Resource temporarily unavailable

### ISSUE THREAD

**Issue by hongyi-zhao** [DogLooksGood/emacs-rime#133]
On Ubuntu 20.10, I installed the emacs-rime from melpa repo. When I'm using it from within emacs, I sometimes noticed the messages shown as below:

```
 $ emacs
E1214 11:21:22.950201 2944205 level_db.cc:277] Error opening db 'luna_pinyin': IO error: lock /home/werner/.local/share/fcitx5/rime/luna_pinyin.userdb/LOCK: Resource temporarily unavailable
```
How to solve this problem?

Regards,
HY

**Comment by DogLooksGood** [comment]
Hi, I never run into this issue, but it looks like your emacs-rime and fcitx5-rime are using the same user directory.

Rime has a system configuration directory, (for example, `/usr/share/rime-data/`), and this configuration will deployed to a few places, each for a single client. Here, emacs-rime and fcitx5-rime are two clients, they should use different directory.

**Comment by hongyi-zhao** [comment]
> but it looks like your emacs-rime and fcitx5-rime are using the same user directory.

You are right, see following for my settings:

```
  :custom
  (default-input-method "rime")
  (rime-share-data-dir "~/.local/share/fcitx5/rime")
```
> Here, emacs-rime and fcitx5-rime are two clients, they should use different directory.

Based on experiences, even with the above settings, this error doesn't happen frequently. BTW, preserver a separated configuration directory for each rime client seems not so convenient. Is there really no way for them to share the configuration directory without trigger any confliction?

**Comment by DogLooksGood** [comment]
This error is come from librime, there's really nothing we can do with librime. 

Users who use pinyin or input methods need dynamically add new words, will use Rime's synchronization feature. 
See section `如何同步词库？` in FAQ.

**Comment by hongyi-zhao** [comment]
Got it. Thanks a lot for your explanation.
