### ISSUE TITLE
[BUG] 需要手动选择 rime 为输入法，posframe 会导致当前buffer处于lose focus的状态

### ISSUE THREAD

**Issue by ziyunch** [DogLooksGood/emacs-rime#134]
**问题描述**

1. rime 的配置无效， ctrl + \ 后需要手动选择 rime 为输入法。
2. 打字时随着 posframe 框的出现，当前 buffer 会处于 lose focus 的状态，一个直观的表现是文字会显示当前设定 posframe 前景色下 lose focus 的略浅的颜色。这样随着 posframe 打字框的出现与消失会造成文字闪烁。

**Emacs中的配置**

```
(use-package rime
  :custom
  (default-imput-method "rime")
  (rime-librime-root (expand-file-name "librime/dist" user-emacs-directory))
  (rime-show-candidate 'posframe)
  (rime-share-data-dir "~/Library/Rime")
  (rime-user-data-dir "~/Library/Rime")
  (rime-posframe-properties
   (list :background-color "#073642"
         :foreground-color "#839496"
         :internal-border-width 1))
  :config
  (set-face-attribute 'rime-default-face nil :foreground "#839496" :background "#073642")
  )
```

**复现方式**（安装遇到问题时省略）

**是否可在 emacs -Q 中复现**

否

**截图**

**环境信息**

- 操作系统：MacOS Catalina
- Emacs版本：如 27.1
- Librime版本：如 1.5.3
- Librime安装方式：包管理器/手工编译
- 安装方式：Melpa

**Comment by DogLooksGood** [comment]
你是否有插件来调整非焦点窗口的颜色？

感觉需要在此类的插件中排除掉 emacs-rime 的 posframe 窗口。

**Comment by cnsunyour** [comment]
emacs -Q 能复现倒是挺稀奇的，题主可否确认 emacs -Q 运行时只加载了 emacs-rime 这一个包呢？

**Comment by ziyunch** [comment]
> 你是否有插件来调整非焦点窗口的颜色？
> 
> 感觉需要在此类的插件中排除掉 emacs-rime 的 posframe 窗口。

我用了 doom-themes，以下是我的配置。请问如何可以排除掉 emacs-rime 的 posframe 窗口呢？一个 data point 是我之前使用 pyim，并无特殊配置，但是它的 posframe 窗口不存在这个问题。

```lisp
(use-package doom-themes
  :after (rime)
  :config
  ;; Global settings (defaults)
  (load-theme 'doom-solarized-dark t)
  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)
  ;; Enable custom neotree theme (all-the-icons must be installed!)
  (doom-themes-neotree-config)
  ;; or for treemacs users
  (setq doom-themes-treemacs-theme "doom-colors") ; use the colorful treemacs theme
  (doom-themes-treemacs-config)
  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config)
  )
;;; Use Doom Theme ends here
```

**Comment by ziyunch** [comment]
> emacs -Q 能复现倒是挺稀奇的，题主可否确认 emacs -Q 运行时只加载了 emacs-rime 这一个包呢？

不好意思，开 issue 的时候没注意这儿。 `emacs -Q` 不能加载 emacs-rime，故不能复现。

**Comment by DogLooksGood** [comment]
感觉 doom emacs 里面有太多东西，目前我没有什么头绪。我觉得可以尝试缩减一下配置来定位原因，有不少用户是使用 doom emacs 的，但是没有这个问题。

**Comment by cnsunyour** [comment]
> > emacs -Q 能复现倒是挺稀奇的，题主可否确认 emacs -Q 运行时只加载了 emacs-rime 这一个包呢？
> 
> 不好意思，开 issue 的时候没注意这儿。 `emacs -Q` 不能加载 emacs-rime，故不能复现。

不是这个意思，意思是你 emacs -Q 启动后，手动只加载 posframe 和 emacs-rime 两个包，然后看一下问题能不能复现。

**Comment by cnsunyour** [comment]
> 感觉 doom emacs 里面有太多东西，目前我没有什么头绪。我觉得可以尝试缩减一下配置来定位原因，有不少用户是使用 doom emacs 的，但是没有这个问题。

我看他说的意思好像是没有用 doom-emacs ，而只是用了 doom-themes 这个包。如果用 doom-emacs 的话是不需要手动 use-package 加载 doom-themes 包的。

**Comment by DogLooksGood** [comment]
因缺乏更多信息关闭。
