### ISSUE TITLE
use-package: :custom wants a non-empty list

### ISSUE THREAD

**Issue by fratcn** [DogLooksGood/emacs-rime#135]
安装报告：
Error (use-package): Failed to parse package rime: use-package: :custom wants a non-empty list

**Emacs中的配置**

```
(defun merat/init-rime ()
  (use-package rime
    :custom
    :init
...
```

**环境信息**

- 操作系统：如 ArchLinux
- Emacs版本：如 27.1
- Librime版本：如 1.6.1
- Librime安装方式：包管理器/pacman

**Comment by DogLooksGood** [comment]
这是  `use-package` 使用的语法问题，`:custom` 后面应有自定义变量的值。
