### ISSUE TITLE
error message 一直出現在  buffer 中 ，該如何處理    謝

### ISSUE THREAD

**Issue by shewer** [DogLooksGood/emacs-rime#137]
如題   要清屏 C-l
另外  (setq rime-posframe-style 'vertical) 垂直無效

**Comment by DogLooksGood** [comment]
是否是使用 Terminal 版本的 Emacs？Terminal 版本的話會有些問題，但好像 daemon + client 模式可以避免。

如果是 Terminal 中，posframe 是不可用的，會回退到使用 popup.el。

**Comment by shewer** [comment]
謝謝     用 daemon mode  ok了
