### ISSUE TITLE
使用posframe做候选框，有时候显示候选词不全

### ISSUE THREAD

**Issue by cnsunyour** [DogLooksGood/emacs-rime#14]
如图：

![image](https://user-images.githubusercontent.com/3713312/76689274-3e3fe800-666f-11ea-8556-1be49b8a0282.png)

第二个候选词是“夜猫子”，好像是 posframe 窗口长度不够所以显示不出来。这种情况在最后一个候选词比前面的长的时候会出现，如果最后一个候选词比前面的短，则显示正常，如图：

![image](https://user-images.githubusercontent.com/3713312/76689323-b4444f00-666f-11ea-8dd4-d75f80e28082.png)

假如把“蠢蠢欲动”排在最后一个，则又会显示不出来

**Comment by DogLooksGood** [comment]
@Z572 
我猜测和宽度的计算有关系，有什么头绪没

**Comment by cnsunyour** [comment]
补充一下，经测，不只是 posframe ，用 popup 也有同样问题

**Comment by DogLooksGood** [comment]
@cnsunyour 你的 emacs 用的字体是什么？

我觉得也许我用相同的字体可以重现这个问题

**Comment by cnsunyour** [comment]
@DogLooksGood 字体是 Sarasa Mono SC

**Comment by DogLooksGood** [comment]
![1584252296](https://user-images.githubusercontent.com/11796018/76696394-f8623e80-66c5-11ea-881a-f1e88010118c.png)

好像重现不了，我从git下载的ttf版本的字体。
有没有试过在其他等宽字体，或字号，或 emacs -Q 下的表现？

**Comment by DogLooksGood** [comment]
怎么感觉看起来不像是同一个字体，你的笔划更粗一些？

**Comment by Z572** [comment]
可能要选择粗体

> 有什么头绪没

会不会和方案有关？

**Comment by Z572** [comment]
@cnsunyour 你是什么打字方案？

**Comment by DogLooksGood** [comment]
我大概有了些思路，比如你发的第一张图里面的，如果用2把第二个选项上屏，会发生什么？我这里有能重现，但是和你说的有区别，如果有不能显示的字符的话，会有这个样子。

![1584253179](https://user-images.githubusercontent.com/11796018/76696584-09ac4a80-66c8-11ea-9ed8-3421c2e10d00.png)
![1584253119](https://user-images.githubusercontent.com/11796018/76696588-0dd86800-66c8-11ea-8aac-77a51edb7ce5.png)

这里的第四个选项是 “”

**Comment by cnsunyour** [comment]
@Z572 五笔，用的码表是这个
https://github.com/KyleBing/rime-wubi86-jidian

**Comment by Z572** [comment]
按理来说 应该显示 5. 的吧
我现在在外边暂时没法测试

**Comment by Z572** [comment]
按理来说 应该显示 5. 的吧

我现在在外边暂时没法测试

**Comment by cnsunyour** [comment]
> 怎么感觉看起来不像是同一个字体，你的笔划更粗一些？

是不是因为是 mac 的关系？

**Comment by Z572** [comment]
> 是 mac 的关系？

字体可以选择粗体，正常，细体斜体之类的

应该和字体没什么关系吧？

**Comment by DogLooksGood** [comment]
@cnsunyour  
可以做一个这样的测试

```
;;; 针对`posframe'
(posframe-hide rime-posframe-buffer)
(posframe-show rime-posframe-buffer
               "yqbb| 1. 底子 2. 夜猫子")

;;; 针对`popup'
(popup-tip "yqbb| 1. 底子 2. 夜猫子")
```

**Comment by Z572** [comment]
会不会是在组合字符串时的时候丢失了后面的字符串

**Comment by cnsunyour** [comment]
> ![1584252296](https://user-images.githubusercontent.com/11796018/76696394-f8623e80-66c5-11ea-881a-f1e88010118c.png)
> 
> 好像重现不了，我从git下载的ttf版本的字体。
> 有没有试过在其他等宽字体，或字号，或 emacs -Q 下的表现？

测试换了字体，表现还是一样。

**Comment by DogLooksGood** [comment]
> 会不会是在组合字符串时的时候丢失了后面的字符串

所以应该用 posframe 和 popup 的 API 直接确认下，确定问题在 emacs-rime 还是 popup或posframe

**Comment by cnsunyour** [comment]
posframe测试结果：
![image](https://user-images.githubusercontent.com/3713312/76696840-c3a4b600-66ca-11ea-8380-0802d388040f.png)

popup测试结果：
![image](https://user-images.githubusercontent.com/3713312/76696813-5e50c500-66ca-11ea-830d-91f58b2fbc60.png)

**Comment by DogLooksGood** [comment]
@cnsunyour 我觉得应该给 posframe 提个 issue。

这个问题应该在 posframe 的层面得到解决。

你那里输入法中的 popup 会展示错误吗？输入法当中对 popup 的使用和这个测试代码几乎是完全一样的。唯一的区别就是编码几个字符有指定 face ，但这样该没有影响才对。

**Comment by cnsunyour** [comment]
不对劲，posframe 那个测试不正常，后来测过多次，显示的是我最后一次在 rime 中输入显示的候选词列表，如我刚刚输入过 wqvb ，则测试结果会是这样：
![image](https://user-images.githubusercontent.com/3713312/76697007-9d801580-66cc-11ea-8114-b318a7e3bc6a.png)

**Comment by cnsunyour** [comment]
> 你那里输入法中的 popup 会展示错误吗？输入法当中对 popup 的使用和这个测试代码几乎是完全一样的。唯一的区别就是编码几个字符有指定 face ，但这样该没有影响才对。

啊，奇怪，popup 又没问题了，昨天晚上明明测试了的啊。

**Comment by DogLooksGood** [comment]
你可以指定其他的buffer名字。不用 `rime-posframe-buffer`，这里给一个其他的字符串，就可以创建一个全新的 posframe

**Comment by cnsunyour** [comment]
执行了，没有任何显示。你看我执行的方法对吗：
![image](https://user-images.githubusercontent.com/3713312/76697275-36fcf680-66d0-11ea-8ec7-5314d4fb7b3d.png)

**Comment by Z572** [comment]
`(posframe-show "buffer-nane" :string "string")`

**Comment by DogLooksGood** [comment]
是我的测试代码给错了。
```
(posframe-show rime-posframe-buffer
               :string "yqbb| 1. 底子 2. 夜猫子")
```
需要 `:string`

**Comment by cnsunyour** [comment]
![image](https://user-images.githubusercontent.com/3713312/76697425-fd2cef80-66d1-11ea-9438-c4b00c055a3d.png)
显示正常，然后马上用 rime 输入代码，还是异常

**Comment by DogLooksGood** [comment]
@cnsunyour 
```
(posframe-show "testbuffer"
               :string
               (concat
                (propertize "yqbb| " 'face font-lock-function-name-face)
                "1. 底子 2. 夜猫子"))
```

**Comment by cnsunyour** [comment]
好像是的
![image](https://user-images.githubusercontent.com/3713312/76697597-20f13500-66d4-11ea-9a6e-47efb917cde1.png)

**Comment by cnsunyour** [comment]
![image](https://user-images.githubusercontent.com/3713312/76697641-952bd880-66d4-11ea-9bfc-c30041081bb5.png)

**Comment by DogLooksGood** [comment]
但是输入法里面还是不对吗？

**Comment by cnsunyour** [comment]
是的，之后又试了，输入法里还是不对

**Comment by DogLooksGood** [comment]
还要试一下这个怎么样
```
(posframe-show "testbuffer"
               :string
               (concat
                (propertize "yqbb| " 'face font-lock-function-name-face)
                "1. 底子 2. 夜猫子")
               :background-color (face-attribute 'rime-posframe-face :background)
		       :foreground-color (face-attribute 'rime-posframe-face :foreground))
```

**Comment by DogLooksGood** [comment]
类似的问题
https://github.com/tumashu/company-posframe/issues/2

**Comment by cnsunyour** [comment]
嗯，基本已经确定是 posframe 的问题了，我先关闭此 issue 了，回头向 posframe 反馈一下
