### ISSUE TITLE
有没有双拼方案？

### ISSUE THREAD

**Issue by wangping-ccp** [DogLooksGood/emacs-rime#144]
通过配置文件可以设置吗？
安装了librime-data-double-pinyin

**Comment by DogLooksGood** [comment]
Welcome to Github

可以，需要配置的就是 rime 的配置。emacs-rime 只是 rime 的一个前端，除了并击的方案，都可以直接使用。

**Comment by swors** [comment]
> Welcome to Github
> 
> 可以，需要配置的就是 rime 的配置。emacs-rime 只是 rime 的一个前端，除了并击的方案，都可以直接使用。

rime/user.yaml里面配置？谢谢

**Comment by DogLooksGood** [comment]
Rime 本身会为每个前端 deploy 一份配置，你可以修改基础的配置，在 linux 中在类似 /usr/share/rime-data 里面。在里面的配置的方式需要参考 rime 的使用文档，通常是改 default.yml 来指定你要用的 rime 的方案。之后在 emacs-rime 启动的时候，会自动的 deploy 一份针对 emacs-rime 的配置。

你也可以修改这份 deploy 好的配置，默认是在 ~/.emacs.d/rime/build/default.yaml 中。
