### ISSUE TITLE
[BUG] linux下会把rime的debug信息输出到窗口

### ISSUE THREAD

**Issue by sharefantasy** [DogLooksGood/emacs-rime#145]
**问题描述**

启动时emacs buffer中会输出大量debug信息, 输入的时候也会输出.

**Emacs中的配置**

```
    (use-package rime
       :custom
       (rime-show-candidate 'popup)
      :hook (after-init . (lambda () (progn
                                        (rime-activate "rime")
                                       (rime-sync)
                                        (rime-lib-select-schema "luna_pinyin_simp"))))
       )
     (setq default-input-method "rime")
```

**复现方式**（安装遇到问题时省略）

启动emacs就遇到

**是否可在 emacs -Q 中复现**

否

**截图**

展示错误的截图或动图
![image](https://user-images.githubusercontent.com/1762046/106082199-36891500-6155-11eb-896f-8d077c9072bc.png)

**环境信息**

- 操作系统：debian 9
- Emacs版本：27.1
- Librime安装方式：guix
- 安装方式：Git

**Comment by DogLooksGood** [comment]
可以尝试用 emacs --daemon + emacsclient -nw 的方式或是使用 gui 的 emacs。
另外，你的配置中使用了 rime-activate，不要这样用，也不要用 hook 全局其用，将其设置为 default-input-method，然后使用 toggle-input-method，emacs 中输入法是 buffer local 的。

librime 1.6 新加了 https://github.com/rime/librime/commit/90839b0b3d47cbfef715ea5f061c7505666ff75d 也许可以解决这个问题了

**Comment by sharefantasy** [comment]
> 可以尝试用 emacs --daemon + emacsclient -nw 的方式或是使用 gui 的 emacs。
> 另外，你的配置中使用了 rime-activate，不要这样用，也不要用 hook 全局其用，将其设置为 default-input-method，然后使用 toggle-input-method，emacs 中输入法是 buffer local 的。
> 
> librime 1.6 新加了 [rime/librime@90839b0](https://github.com/rime/librime/commit/90839b0b3d47cbfef715ea5f061c7505666ff75d) 也许可以解决这个问题了

好的谢谢!我试试看
目前我是远程使用emacs, 所以只能是TUI的了. 但是好像这个问题在macOS的TUI上没有复现

**Comment by DogLooksGood** [comment]
@sharefantasy 你可以使用 emacs --daemon 然后用 emacsclient -nw 来启动 tui 。这个方式也可以。
