### ISSUE TITLE
[BUG]小鹤双拼方案设定为简中时部分输入结果错误

### ISSUE THREAD

**Issue by Novite5** [DogLooksGood/emacs-rime#146]
**问题描述**

小鹤双拼方案设定默认为简中时部分输入结果错误
例如：输入 lun 显示的候选项为 “乱 卵 栾 鸾 峦”。

**Emacs中的配置**

```
(use-package rime
  :custom
  (default-input-method "rime"))
```

**复现方式**（安装遇到问题时省略）

在小鹤双拼输入方案的 double_pinyin_flypy.custom.yaml 文件中设置默认为简体
或者在 [cloverpinyin](https://github.com/fkxxyz/rime-cloverpinyin) 方案的 custom 文件中将输入模式替换为小鹤双拼

**环境信息**

- 操作系统：如 ArchLinux
- Emacs版本：27.1
- Librime版本：1.7.0
- Librime安装方式：包管理器
- 安装方式：Melpa

**Comment by DogLooksGood** [comment]
emacs-rime 只是输入法前端，应该和你的输入法方案是没有关系的。

你应该用小鹤双拼的 schema，然后在 translator -> dictionary 处指定 clover。

**Comment by Novite5** [comment]
> emacs-rime 只是输入法前端，应该和你的输入法方案是没有关系的。
> 
> 你应该用小鹤双拼的 schema，然后在 translator -> dictionary 处指定 clover。

@DogLooksGood 
我的意思是：我小鹤 double_pinyin_flypy 和 将 clover 改成小鹤的双拼 两者都试了。小鹤在默认繁体中文的时候，就一切正常。clover 如果是默认配置，即没有改成小鹤双拼，也是正常的。而在 ibus-rime 下，没有出现这种情况。
