### ISSUE TITLE
我用的是emacs26.1，是没法用吗？

### ISSUE THREAD

**Issue by xukongwen** [DogLooksGood/emacs-rime#147]
**问题描述**

简明的问题描述

**Emacs中的配置**

```
(use-package rime
  :custom
  (default-input-method "rime"))
```

**复现方式**（安装遇到问题时省略）

复现问题所需的操作

**是否可在 emacs -Q 中复现**

是/否

**截图**

展示错误的截图或动图

**环境信息**

- 操作系统：如 ArchLinux
- Emacs版本：如 27.0.90
- Librime版本：如 1.5.3
- Librime安装方式：包管理器/手工编译
- 安装方式：Git/Melpa/Straight/Quelpa

**Comment by DogLooksGood** [comment]
如果是 Emacs 26.1 的话，需要手功编译开启 dynamic module 的支持。

在 Emacs 27+ 里面已经默认打开。

缺乏 26 相关的测试，建议用 27 以上的版本。
