### ISSUE TITLE
候选词未上屏时关闭 rime ，候选框不消失

### ISSUE THREAD

**Issue by cnsunyour** [DogLooksGood/emacs-rime#15]
对比如下两图：
![image](https://user-images.githubusercontent.com/3713312/76689413-ac38df00-6670-11ea-970c-f38e43971891.png)

此时按 C-\ 关闭输入法，候选框仍然显示：
![image](https://user-images.githubusercontent.com/3713312/76689430-bfe44580-6670-11ea-87a4-03f38a6e604e.png)

这时移动光标不会使候选框消失，只有输入一个字符才会消失。

**Comment by DogLooksGood** [comment]
0d1c61ea9cb69adbd695905639ff1a741f7d6a60

已处理

**Comment by cnsunyour** [comment]
OK了
