### ISSUE TITLE
[BUG] vterm中无法输入词语

### ISSUE THREAD

**Issue by passchaos** [DogLooksGood/emacs-rime#152]
**问题描述**
当在vterm中使用时，如果输入2个汉字以上时，无法使用空格或者数字选中候选词，只输入一个字时可以正常使用
![image](https://user-images.githubusercontent.com/8736961/112427451-9296a100-8d74-11eb-9518-b61ca92d77ec.png)

**Emacs中的配置**

```
(use-package rime
  :custom
  (default-input-method "rime")
  (setq rime-show-candidate 'posframe)
  )
```

**复现方式**

在vterm buffer中使用emacs-rime

**截图**
开启debug-on-error后，在vterm中输入中文会停留在如下地方
![image](https://user-images.githubusercontent.com/8736961/112427154-14d29580-8d74-11eb-8d0b-762dd3600f14.png)

**环境信息**

- 操作系统：ArchLinux
- Emacs版本： GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-03-25
- Librime版本： 1.7.3
- Librime安装方式：包管理器
- 安装方式：Melpa

**Comment by passchaos** [comment]
> **问题描述**
> 当在vterm中使用时，如果输入2个汉字以上时，无法使用空格或者数字选中候选词，只输入一个字时可以正常使用
> ![image](https://user-images.githubusercontent.com/8736961/112427451-9296a100-8d74-11eb-9518-b61ca92d77ec.png)
> 
> **Emacs中的配置**
> 
> ```
> (use-package rime
>   :custom
>   (default-input-method "rime")
>   (setq rime-show-candidate 'posframe)
>   )
> ```
> 
> **复现方式**
> 
> 在vterm buffer中使用emacs-rime
> 
> **截图**
> 开启debug-on-error后，在vterm中输入中文会停留在如下地方
> ![image](https://user-images.githubusercontent.com/8736961/112427154-14d29580-8d74-11eb-8d0b-762dd3600f14.png)
> 
> **环境信息**
> 
> * 操作系统：ArchLinux
> * Emacs版本： GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-03-25
> * Librime版本： 1.7.3
> * Librime安装方式：包管理器
> * 安装方式：Melpa

It's a vterm bug

**Comment by jixiuf** [comment]
https://github.com/jixiuf/emacs-libvterm/commit/2b1392cb2b14ec5bd0b7355197d5f353aa5d3983 应该修复了这个问题。

**Comment by jixiuf** [comment]
理论上 vterm 应该已经支持各种输入法了，应该不需要 rime.el 里做各种兼容了。 像 rime--init-hook-vterm ，
我没仔细验证，精略的将 rime--init-hook-vterm 中的内容注掉后，依然可以在vterm 中使用输入法。
可以试着清理下代码了。
