### ISSUE TITLE
[BUG] commit_comment 不立即上屏，而是下一次輸入旳時候才上屏

### ISSUE THREAD

**Issue by nasyxx** [DogLooksGood/emacs-rime#153]
**问题描述**

commit_comment 不立即上屏，而是下一次輸入旳時候才上屏

比如，此時我按 `C-SPC` 應該上屏 `啊`（即 tips 內容）。然而甚麼也沒上屏

<img width="258" alt="Screen Shot 2021-03-30 at 02 45 28 AM" src="https://user-images.githubusercontent.com/5007613/112945213-fec12e00-9101-11eb-86be-41e5b00b4f4e.png">

<img width="318" alt="Screen Shot 2021-03-30 at 02 45 37 AM" src="https://user-images.githubusercontent.com/5007613/112945264-0e407700-9102-11eb-8159-131dfc598d67.png">

當我再次按任意按鍵旳時候，這个 `啊` 上屏了。

<img width="354" alt="Screen Shot 2021-03-30 at 02 46 48 AM" src="https://user-images.githubusercontent.com/5007613/112945361-2dd79f80-9102-11eb-85c7-c10d25254944.png">

**Emacs中的配置**

```elisp
(leaf rime
  :doc "RIME ㄓ in Emacs"
  :url "https://github.com/DogLooksGood/emacs-rime"
  :tag "convenience" "input-method"
  :bind
  (:rime-mode-map
   ("C-`"   . rime-send-keybinding)
   ("C-S-`" . rime-send-keybinding)
   ("C-,"   . rime-send-keybinding))
  (:rime-active-mode-map
   ("C-;"   . rime-send-keybinding)
   ("C-SPC" . rime-send-keybinding))
  :custom
  `(rime-librime-root   . ,(expand-file-name "~/.nix-profile"))
  `(rime-user-data-dir  . ,(expand-file-name "~/.config/rime"))
  (default-input-method . "rime")
  (rime-cursor          . "˰")
  (rime-show-candidate  . 'posframe)
  (rime-posframe-style  . 'vertical)
  (rime-show-preedit    . t)
  (rime-translate-keybindings
   . '("C-f"
       "C-b"
       "C-n"
       "C-p"
       "C-g"
       "C-`"
       "C-SPC"
       "<left>"
       "<right>"
       "<up>"
       "<down>"
       "<prior>"
       "<next>"
       "<delete>")))
```

**rime**

要使用這个功能，需要在 `xxx.schema.yaml` 旳 `editor/bindings` 部分添加

```yaml
editor:
  bindings:
    Control+Return: commit_comment
    Control+space: commit_comment
```

**环境信息**

- 操作系统： macOS 11.2.3
- Emacs版本： 28
- Librime版本： master
- Librime安装方式：nix 手勭
- 安装方式：straight

**Comment by DogLooksGood** [comment]
fixed in 83bf8de595f9b82dae229b75244a214797b5f841
