### ISSUE TITLE
[FEATURE] 希望可以使用自定义候选标签

### ISSUE THREAD

**Issue by nasyxx** [DogLooksGood/emacs-rime#154]
**问题描述**

希望可以一下使用自定义候选标签，如 苏州码子 `'("〡" "〢" "〣" "〤" "〥" "〦" "〧" "〨" "〩")`

default.yaml 里面这儿可以得到

![IMAGE 2021-04-08 21:49:42](https://user-images.githubusercontent.com/5007613/114117269-54d96280-98b4-11eb-80bc-1347cb61f298.jpg)

![IMAGE 2021-04-08 21:50:44](https://user-images.githubusercontent.com/5007613/114117331-79cdd580-98b4-11eb-8ecc-1dc6c947fe52.jpg)

**Comment by DogLooksGood** [comment]
我看了提交的 PR，虽然可以解决问题，但我更倾向于从 librime 读到数据。目前没有直接读 yaml 的好办法，因为 rime 的配置实际上是可以有继承关系的，并不是读哪个文件就一定能得到想要的信息。我需要看下通过 rime api 的解决方案。

**Comment by DogLooksGood** [comment]
Feature added.
