### ISSUE TITLE
[FEATURE] Add debounce to reduce the searching lagging

### ISSUE THREAD

**Issue by ztlevi** [DogLooksGood/emacs-rime#157]
**问题描述**

目前rime 在输入的过程中没有debounce的feature，这个类似与company-idle-delay，在用户停止输入比方说0.3s后再进行搜索。

因为doom在emacs下的org-mode中，如果有大片中文，就会比较卡，每次如果输入一个字符就rime就进行搜索的话就会很卡。

**Emacs中的配置**

https://github.com/ztlevi/doom-config/blob/company/+misc.el#L19

**复现方式**（安装遇到问题时省略）

复现问题所需的操作

**环境信息**

- 操作系统：如 Macos
- Emacs版本：如 28.0.50
- Librime版本：如 1.7.2
- Librime安装方式：包管理器
- 安装方式：Straight

**Comment by DogLooksGood** [comment]
输入法并不能这样处理，因为在输入法处理完成前键盘事件是无法生效的。比如你按了 a，如果输入法不决定是该候选 “阿” 还是该上屏 “a”，就没有办法确定下一步的输入该如何处理。

librime 的性能本身也足够好，所有的 rime 前端都不会做延迟加载的逻辑。

doom 的 org 卡更像是 doom 的一个bug，这个问题应该从 doom 的角度去解决。

**Comment by ztlevi** [comment]
好吧，那我还是close了吧。
