### ISSUE TITLE
[BUG] 默认参数internal-border-width为10显示异常

### ISSUE THREAD

**Issue by chenzaichun** [DogLooksGood/emacs-rime#159]
**问题描述**

当参数默认为10的情况下，候选词选择会显示不全。

**Emacs中的配置**

```
  (use-package rime
    :custom
    (default-input-method "rime")
    )
  (setq rime-user-data-dir "~/RimeEmacs/")
```
  (setq default-input-method "rime"
        rime-show-candidate 'posframe)
  (setq rime-inline-ascii-trigger 'shift-l)

**复现方式**（安装遇到问题时省略）

字体为 `Sarasa Mono SC Nerd 22`

**是否可在 emacs -Q 中复现**

是/否

**截图**

![image](https://user-images.githubusercontent.com/127616/117386796-15854c80-af1a-11eb-9f87-110e9e55c176.png)

**环境信息**

- 操作系统：如 Ubuntu 20.04
- Emacs版本：如 28.0.50 (pgtk branch)
- Librime版本：如 1.5.3
- Librime安装方式：手工编译
- 安装方式：Melpa

**Comment by DogLooksGood** [comment]
我怀疑是在 pgtk 上特有的问题？

**Comment by chenzaichun** [comment]
恩，我重新用 `master` 分支编译了一版，测试没有问题，就像你说的那样，应该是 `pgtk` 上特有的问题。

**Comment by DogLooksGood** [comment]
嗯，这边先关闭了，可以在 posframe 项目开个 issue。
