### ISSUE TITLE
Mac emacs-mac 27.2 Compile Rime dynamic module failed

### ISSUE THREAD

**Issue by nicehiro** [DogLooksGood/emacs-rime#162]
**问题描述**
之前一直是可用的，今天把所有 package 删掉重新安装了一遍之后，发现一直报错 Compile Rime  dynamic module failed.

在 https://github.com/DogLooksGood/emacs-rime/issues/26#issuecomment-601527122 我尝试直接直接编译了一下：

![image](https://user-images.githubusercontent.com/17773634/118400179-1abd6680-b693-11eb-9218-42e21536b0f2.png)

然后又找到这里 https://github.com/DogLooksGood/emacs-rime/issues/71 ，但仍然没有解决方法

**Emacs中的配置**

```
(use-package rime
	:bind
	(:map
	 rime-active-mode-map
	 ("M-j" . 'rime-inline-ascii)
	 :map rime-mode-map
	 ("C-$" . 'rime-send-keybinding)
	 ("M-j" . 'rime-force-enable)
	 ("C-\\" . 'toggle-input-method))
	:custom
	(
	 (rime-translate-keybindings '("C-f" "C-b" "C-n" "C-p" "C-g"))
	 (default-input-method "rime")
	 (rime-cursor "˰")
	 (rime-show-candidate 'posframe)
	 (rime-posframe-style 'vertical)
	 (rime-posframe-properties (list :background-color (frame-parameter nil 'background-color)
																	 :foreground-color (frame-parameter nil 'foreground-color)))
	 (rime-disable-predicates '(rime-predicate-evil-mode-p
															rime-predicate-after-alphabet-char-p
															rime-predicate-prog-in-code-p
															rime-predicate-tex-math-or-command-p
															rime-predicate-current-uppercase-letter-p
															rime-predicate-ace-window-p
															rime-predicate-after-ascii-char-p))
```

**复现方式**（安装遇到问题时省略）

```
(rime-compile-module)
```

**是否可在 emacs -Q 中复现**

是

**环境信息**

- 操作系统：Mac
- Emacs版本：emacs-mac 27.2
- Librime版本：1.7.3
- Librime安装方式：文档推荐方式，下载的release文件
- 安装方式：Melpa + use-package

**Comment by yuanl** [comment]
我也遇到了，我的 Emacs 是用 macports 安装的。还需要设置 `rime-emacs-module-header-root`

```elisp
(use-package! rime
  :custom
  (rime-librime-root "/opt/local/")
  (rime-emacs-module-header-root "/Applications/MacPorts/Emacs.app/Contents/Resources/include/")
  (default-input-method "rime"))
```
目前是这么解决的，应该还有更好的方法。

**Comment by nicehiro** [comment]
> 我也遇到了，我的 Emacs 是用 macports 安装的。还需要设置 `rime-emacs-module-header-root`
> 
> ```emacs-lisp
> (use-package! rime
>   :custom
>   (rime-librime-root "/opt/local/")
>   (rime-emacs-module-header-root "/Applications/MacPorts/Emacs.app/Contents/Resources/include/")
>   (default-input-method "rime"))
> ```
> 
> 目前是这么解决的，应该还有更好的方法。

谢谢，这样确实可以。

**Comment by vizmoe** [comment]
如果是 macOS Emacs Plus，提示 ‘emacs-module.h' not found，需要将 `rime-emacs-module-header-root` 设置为 `opt/homebrew/include/`
