### ISSUE TITLE
emacs-rime项目已经很久没发布新版本号了

### ISSUE THREAD

**Issue by pmeiyu** [DogLooksGood/emacs-rime#169]
**问题描述**

emacs-rime项目已经很久没发布新版本号了，可以考虑定期发个版本号吗？这样方便各个发行版打包。由于emacs-rime项目含有需要编译的C语言组件，用包管理器安装时可以自动解决编译问题，比从melpa安装更方便。定期发布版本号会对包管理器更友好。

**Comment by DogLooksGood** [comment]
已更新 v1.0.5
