### ISSUE TITLE
EXWM图形界面中无法输入中文

### ISSUE THREAD

**Issue by zhenhua-wang** [DogLooksGood/emacs-rime#172]
**问题描述**

- 请问在exwm的正确设置是什么？我在使用EXWM时，emacs内部的buffer都可以正常使用rime，但是在EXWM调用的图形界面（比如，qutebrowser）中无法输入中文。我状态栏里显示rime是开启的状态，但是输入时只能输入英文字母，而且minibuffer中没有出现任何中文选词。

**Emacs中的配置**

```
  (use-package rime
    :custom
    (default-input-method "rime")
    :config
    ;; (rime-lib-select-schema "luna_pinyin_simp")
    (setq rime-show-candidate 'sidewindow)
    (setq rime-translate-keybindings
          '("C-f" "C-b" "C-n" "C-p" "C-g" "<left>" "<right>" "<up>" "<down>" "<prior>" "<next>" "<delete>")))
```

**复现方式**（安装遇到问题时省略）

在EXWM的图形buffer中切换RIME并输入

**是否可在 emacs -Q 中复现**

否, EXWM才会出现问题

**截图**

展示错误的截图或动图

**环境信息**

- 操作系统： ArchLinux
- Emacs版本：27.2
- Librime版本：1.7.2
- Librime安装方式：包管理器 pacman
- 安装方式：use package

**Comment by Z572** [comment]
https://github.com/ch11ng/exwm/blob/0368127976bda29d35eed788edfe74644ecd3845/exwm-xim.el#L44-L62

**Comment by zhenhua-wang** [comment]
Thanks, I have the exact same setting, but it just don't work for me. I guess this is an EXWM problem. I'll close this issue
