### ISSUE TITLE
切换输入法一直显示重新部署

### ISSUE THREAD

**Issue by vinurs** [DogLooksGood/emacs-rime#173]
**问题描述**
其它应用中切换输入法的时候显示重新部署，如果关闭Emacs那么就不会出现这个现象

**Emacs中的配置**

```
(use-package rime
  :demand :after (which-key)
  :custom
  (default-input-method "rime")
  (rime-user-data-dir "~/Library/Rime/")
  (rime-librime-root "~/.emacs.d/librime/dist")
  (rime-emacs-module-header-root "/Applications/Emacs.app/Contents/Resources/include")
  )

```

**截图**

![Kapture 2021-09-05 at 17 07 07](https://user-images.githubusercontent.com/37489300/132121657-d3d0654e-4633-4b89-b9b4-f0809e633aa4.gif)

**环境信息**

- 操作系统：macos 11.5.2
- Emacs版本：如 28.0.50
- Librime版本：如 1.7.3
- Librime安装方式：下载解压
- 安装方式：melpa

**Comment by DogLooksGood** [comment]
不能和系统的输入法使用相同的 data 目录。Rime 对于每个前端实现需要有自己的 user data 目录。
