### ISSUE TITLE
[BUG]设置rime-show-candidate nil后，minibuffer仍然会出现候选框

### ISSUE THREAD

**Issue by subego** [DogLooksGood/emacs-rime#175]
**问题描述**

设置rime-show-candidate nil后，使用swiper consult-goto-line时，minibuffer仍然会出现候选框。

**Emacs中的配置**

```
(use-package rime
  :straight (rime :host github
                  :repo "DogLooksGood/emacs-rime"
                  :files ("*.el" "Makefile" "lib.c"))
  :custom
  (default-input-method "rime")
  (rime-librime-root "~/.emacs.d/librime/dist")
  (rime-show-candidate nil))
```

**截图**
<img width="589" alt="CleanShot 2021-09-10 at 23 18 21@2x" src="https://user-images.githubusercontent.com/3454566/132877233-09e1cea1-7063-4b6e-8510-771f6decd885.png">
设置(rime-show-candidate nil)之后，buffer中正常。
<img width="596" alt="CleanShot 2021-09-10 at 23 17 30@2x" src="https://user-images.githubusercontent.com/3454566/132877118-f8f57c0d-b2fb-4ca8-a76e-788d9ba18243.png">
minibuffer中仍然有候选框。

**环境信息**

- 操作系统：macOS 11.5.2
- Emacs版本：emacs-mac-port 27.2
- 安装方式：Straight

**Comment by DogLooksGood** [comment]
已修复
