### ISSUE TITLE
[BUG?] rime-active-mode-map 中绑定 Shift+[a-z] 无效

### ISSUE THREAD

**Issue by alexluigit** [DogLooksGood/emacs-rime#178]
**问题描述**

开发者你好，我遇到的问题是:

无法在 rime-active-mode-map 中转发 `Shift+[a-z]` 键

**Emacs中的配置**

```
(use-package rime
  :custom
  (default-input-method "rime")
  :config
  (push "S-t" rime-translate-keybindings))

;; 或者

(use-package rime
  :custom
  (default-input-method "rime")
  :bind
  (:map rime-active-mode-map
        ("S-t" . (lambda () (interactive) (message "hello")))))
```

**复现方式**（安装遇到问题时省略）

rime 开启状态下输入 `Shift+[a-z]` (例如 `Shift+t`)，`T` 会直接上屏，似乎没有被直接转发给 librime?
在我的输入方案里大写字母是用于其他功能的 (Composing 时不会上屏)，使用 fcitx5 没有此问题。

**是否可在 emacs -Q 中复现**

是

**截图**

![Peek 2021-11-12 16-01](https://user-images.githubusercontent.com/16313743/141432393-7d590644-5470-4902-a1ad-d61e80fa23e8.gif)

**环境信息**

- 操作系统：ArchLinux
- Emacs版本：29.0.50
- Librime版本：1.7.3
- Librime安装方式：包管理器/手工编译 (都不行)
- 安装方式：Straight

**Comment by DogLooksGood** [comment]
如果不是 emacs-rime ，系统的 rime 收到大写字母会做何处理？有基于大写字母的编码吗？

**Comment by alexluigit** [comment]
没有基于大写字母的编码，但有通过 librime-lua 将大写字母绑定到别的功能 (在 fcitx5 下可以正常识别)。
实现方式是在方案中新增一个 engine/processors, 这个 processor 可以截获所有键盘事件并进行收拒处理。
其实这个这个方案也截获了小写字母和并做了一些额外处理，在 emacs-rime 下是可以被 librime 收到的。
fcitx5 截图:

![Peek 2021-11-17 17-03](https://user-images.githubusercontent.com/16313743/142170558-7573c509-6ea9-4b25-a069-b6f0e55a65e6.gif)
(句子输入完成后我按了 Shift+t 移动光标)

以下是 lua 脚本中判断大写的代码 (如果和这个有关系的话):
```lua
-- 大写 A-Z
function Key:is_upper ()
  return self.kCode > 0x40 and self.kCode <= 0x5a
end
```

**Comment by DogLooksGood** [comment]
大写字母实际上是发到了 librime 的，所有你看到的候选或嵌入的文本，都是 librime 返回。如果在我这里，按大写的话，输入不停止，是这个样子


![image](https://user-images.githubusercontent.com/11796018/142180966-ca0c9068-3909-4a0e-a0e3-e91cce9343c2.png)

当然这个 xdeT 都是 librime 这边返回的内容，所以是正常发送到了。但是你那里说直接上屏的话，我觉得有可能是 lua 插件没有加载？我没有用过 lua 的插件，不知道是个什么样的机制。

没有办法通过在 rime-active-map 上面绑定单键达到想要的效果，因为单键的命令被输入法处理之后才能产生输入事件，有了输入事件才有 keymap 的事情。

**Comment by alexluigit** [comment]
我明白了，原来是因为 emacs-rime 转发的按键名和 fcitx5 不一样。(emacs-rime 发送 "T"，fcitx5 发送 "Shift+t")。
感谢答复！
