### ISSUE TITLE
如何修改激活快捷键？

### ISSUE THREAD

**Issue by jason--liu** [DogLooksGood/emacs-rime#184]
默认快捷键是Ctl+\，请问如何修改，比如修改成Ctl+SPC。

**Comment by zhuatw** [comment]
我也想知道, 另外可不可以, 设置成 F3, F4 这类的

**Comment by DogLooksGood** [comment]
这样的配置是 rime 配置中设置的。
在 emacs-rime 中，只需要把对应的组合键发送到 rime 。

```
(define-key rime-mode-map (kbd "C-`") 'rime-send-keybinding)
```
用这样的方式。

**Comment by zhuatw** [comment]
打扰了, 基本可以了,  还有一些问题, 属于 个性化的了, 不麻烦了, 因为我用的是 李大侠的 xah-fly-mode, 在有些地方会不一致, 因为我是改变 miniline  来用顔色来区别是否在, 英文的状态 还是在 中文的状态, 这样更 直观些

**Comment by DogLooksGood** [comment]
是的，如果你觉得 rime-lighter 的颜色变化不够明显的话。

**Comment by DogLooksGood** [comment]
> 默认快捷键是Ctl+\，请问如何修改，比如修改成Ctl+SPC。

不好意思，你指的应该是切换输入法的按键。那个命令叫 `toggle-input-method` ，你用 `C-h k C-\` 就可以查到，然后绑在任意你想绑的按键上都可以。
