### ISSUE TITLE
Feature request：做一个fcitx5的前端

### ISSUE THREAD

**Issue by QiangF** [DogLooksGood/emacs-rime#185]
看到这里有个包通过Dbus和fcitx通信，这样系统所有的输入都用一套配置，还能解决eaf系统输入发选词框位置的问题。
https://github.com/tonyfettes/fcitx5.nvim

**Comment by DogLooksGood** [comment]
没有这样的计划，现在的 emacs-rime 完全符合我的需求。

**Comment by QiangF** [comment]
work in progress
https://github.com/QiangF/emacs-dbus-proxy

**Comment by QiangF** [comment]
Done! https://github.com/QiangF/imbot
