### ISSUE TITLE
在 Fedora 中安装使用时需要先安装 librime-devel

### ISSUE THREAD

**Issue by pulcinello** [DogLooksGood/emacs-rime#189]
如题。我在 Fedora 34 上按 INSTALLATION.org 中的说明安装完 librime, emacs-devel 后仍会在 compiling dynamic module 时报错。安装 librime-devel 后问题解决。希望 INSTALLATION.org 中能得到修改，谢谢。

**Comment by DogLooksGood** [comment]
是 librime 和 librime-devel 都需要吗？

**Comment by pulcinello** [comment]
librime-devel 在 Fedora 34 里依赖 librime。所以说明里只写 librime-devel 应该就可以了。

**Comment by DogLooksGood** [comment]
已更新，谢谢！
