### ISSUE TITLE
rime-mode-map 空格只能首选上屏

### ISSUE THREAD

**Issue by Z572** [DogLooksGood/emacs-rime#19]
无法设置为其他函数

**Comment by DogLooksGood** [comment]
emacs中的输入法对于单键的输入可以接收到除了127(DEL)以外的所有的输入，所以有专门的函数来处理 backspace 行为和处理 esc 的取消行为。不考虑添加其它的函数，return对应的函数计划移除。

你可以在 rime-mode-map 上面给 SPC 绑定自定义的函数来完成定制功能，但本项目不考虑添加额外的逻辑。

**Comment by Z572** [comment]
> 在 rime-mode-map 上面给 SPC 绑定自定义的函数
空格键绑了和没绑一样效果
除了空格键其他绑定都有用

**Comment by DogLooksGood** [comment]
似乎是被输入法拦截了，输入法的优先级高于所有的 mode.

除了 DEL 都会被输入法处理。
所以绑定字母，空格之类的都没有用。

**Comment by Z572** [comment]
https://www.gnu.org/software/emacs/manual/html_node/emacs/Input-Methods.html#Input-Methods
可能有用

**Comment by DogLooksGood** [comment]
我并不希望添加一个机制来干预input method的按键处理流程。

**Comment by Z572** [comment]
好吧

**Comment by DogLooksGood** [comment]
如果这个功能是 Rime 自身可以实现的，通过 Rime 自身配置去完成更合理。

这样可以在所有的地方得到这个效果。
