### ISSUE TITLE
[FEATURE] 光标颜色指示器

### ISSUE THREAD

**Issue by harry-xiaomi** [DogLooksGood/emacs-rime#190]
通过光标颜色快速判断当前处于的中/英输入状态，比 modeline 更方便。

pyim 默认同时启用 modeline 和光标颜色指示器 `pyim-indicator-with-cursor-color`。

**Comment by DogLooksGood** [comment]
我觉得 emacs-rime 不能加入光标颜色的指示器，原因是 Emacs 中的输入法是一个 buffer local 的概念，每个 buffer 中有独立的状态。而光标的颜色是全局的。用一个全局的样式来指示一个 buffer local 的状态是不合理的。

**Comment by DogLooksGood** [comment]
我觉得 emacs-rime 不能加入光标颜色的指示器，原因是 Emacs 中的输入法是一个 buffer local 的概念，每个 buffer 中有独立的状态。而光标的颜色是全局的。用一个全局的样式来指示一个 buffer local 的状态是不合理的。

**Comment by harry-xiaomi** [comment]
可以理解，用户统一做全局的光标颜色管理比某一个包做更合适。
