### ISSUE TITLE
doom emacs注音輸入在return後會變成英文

### ISSUE THREAD

**Issue by katzecase** [DogLooksGood/emacs-rime#206]
**问题描述**

注音輸入後，用return上屏時會變回英文。
但如果輸入標點符號就能上屏。

我不確定這是不是bug，如果是有什麼其他需要進行設置的部份，也請指點一下 :)

**Emacs中的配置**

```
(use-package rime
  :custom
  (default-input-method "rime")
  (rime-show-candidate 'posframe)
  (rime-posframe-style 'vertical))
```

**复现方式**（安装遇到问题时省略）

使用注音輸入中文，無論有沒有選定候選字，return後都會變成英文。

**是否可在 emacs -Q 中复现**

是/否

**截图**

不會放截圖，給圖床的[網址](https://imgur.com/a/ndyBLzY)

**环境信息**

- 操作系统：manjaro
- Emacs版本：28.2
- Librime版本：1.7.3
- Librime安装方式：pacman
- 安装方式：Melpa

**Comment by DogLooksGood** [comment]
这是预期行为，上屏是用空格，return 是上屏原编码。我理解 rime 中本身也是这样的。

**Comment by katzecase** [comment]
> 这是预期行为，上屏是用空格，return 是上屏原编码。我理解 rime 中本身也是这样的。

拼音的話空格可以上屏；但用注音輸入時，空格只會取消候選，再次空格會重新打開候選。
[截圖](https://imgur.com/a/nvVTmJV)

**Comment by katzecase** [comment]
好像是注音的yaml配置問題，註解掉
```yaml
editor:
  bindings:
    space: toggle_selection
```
就可以用空格上屏
