### ISSUE TITLE
minibuffer中使用存在一些问题

### ISSUE THREAD

**Issue by DogLooksGood** [DogLooksGood/emacs-rime#21]
- minibuffer中的候选还是应该遵循用户的设置
- minibuffer中按 <kbd>ESC</kbd> 取消后不能正确的清理嵌入文本
- 不能在isearch中使用

**Comment by DogLooksGood** [comment]
#25

**Comment by Z572** [comment]
``` elisp
(defun rime--init-minibuffer ()
  "Initializer for minibuffer when input method is enabled.

Currently just deactivate input method."
  (unless (eq input-method-function 'rime-input-method)
      (deactivate-input-method)))
```
也可以

**Comment by DogLooksGood** [comment]
还有个问题
![isearch-bug](https://user-images.githubusercontent.com/11796018/77076056-3c3ea600-6a2e-11ea-8b65-d1c1d0942334.gif)

好像顶上去之后（类似五笔也会有这样的问题），编码候选不会显示出来。
或者是显示出来了但是被 isearch 刷掉了，他要显示搜索结果的信息。

**Comment by Z572** [comment]
我之前看到过一个在 isearch 提示符里显示上次搜索内容的函数, 等我找一找

**Comment by Z572** [comment]
> Display last searched string in minibuffer prompt

``` elisp
 (add-hook 'isearch-mode-hook (lambda () (interactive)
   (setq isearch-message (concat isearch-message "[ " (car search-ring) " ] "))
   (isearch-search-and-update)))
```

**Comment by DogLooksGood** [comment]
并不能解决我说的问题，但是用phi-search可以解决。

> ```emacs-lisp
> (defun rime--init-minibuffer ()
>   "Initializer for minibuffer when input method is enabled.
> 
> Currently just deactivate input method."
>   (unless (eq input-method-function 'rime-input-method)
>       (deactivate-input-method)))
> ```
> 
> 也可以


这样不行的，会失去 minibuffer 自动英文的功能。
我现在觉得使用 phi-search 是个不错的办法，好像可以直接解决所有问题。

**Comment by Z572** [comment]
我好像没有遇到这个问题
![isearch](https://user-images.githubusercontent.com/37945516/77078429-870ded00-6a31-11ea-9728-e534c849ab1c.gif)

**Comment by DogLooksGood** [comment]
因为拼音输入法不存在顶字上屏的场景。

**Comment by Z572** [comment]
> 不存在顶字上屏

好吧
> phi-search 

是什么?

**Comment by DogLooksGood** [comment]
https://github.com/zk-phi/phi-search

这个的实现比较像现代的这些插件，和 isearch是完全一样的按键和功能。
我在考虑要不要在文档中建议使用。

**Comment by Z572** [comment]
backspace 会被覆盖 , #6 应该重新打开
![6](https://user-images.githubusercontent.com/37945516/77079321-cd178080-6a32-11ea-8e8c-7869203b6831.gif)

**Comment by DogLooksGood** [comment]
计划在文档中添加使用 phi-search.

**Comment by DogLooksGood** [comment]
@Z572 `rime--init-minibuffer` 是放在全局的hook上面，但是输入法在任何 buffer 都可以关闭，这会不会有问题。 用 minibuffer-exit-hook 怎么样？

**Comment by Z572** [comment]
但用 minibuffer-exit-hook 取消有一点问题

**Comment by Z572** [comment]
我怀疑是 rime--minibuffer-messae 影响的, 取消需要三次

**Comment by Z572** [comment]
又或者是因为 rime-translate-keybindings 里的 <kbd> C-g </kbd> 影响的

**Comment by DogLooksGood** [comment]
我觉得要尽量不使用 minibuffer-init-hook，好像用 minibuffer-exit-hook 配合 with-minibuffer-selected-window 并没有效果。下次进来的时候还输入法还是激活的

**Comment by Z572** [comment]
哦, 三次是正常的,

> Signature
(minibuffer-keyboard-quit)

> Documentation
Abort recursive edit.

> In Delete Selection mode, if the mark is active, just deactivate it;
then it takes a second C-g to abort the minibuffer.

**Comment by DogLooksGood** [comment]
找到比较好的办法了。我会提交到 inline 的分支。
