### ISSUE TITLE
[question] 如何在切换输入法时首项自动上屏

### ISSUE THREAD

**Issue by ATNewHope** [DogLooksGood/emacs-rime#211]
如题。
fcitx5 的 rime 是支持这个功能的，即切换到别的语言时，当前输入法的首项自动上屏。

我的想法是，自定义一个函数，替代原本的 `toggle-input-method` ：
```elisp
(defun toggle-input-method-autoselect()
      (interactive)
      (rime-insert-first-item)
      (toggle-input-method))
```
然后再把这个 `toggle-input-method-autoselect` 绑定到原先 `toggle-input-method` 所在的键位上即可。

这里的 `(rime-insert-first-item)` 是我虚构的函数，功能是：
- 未开启输入法时，什么也不做；
- 开启输入法时，
  + 若不存在待上屏的字，什么也不做；
  + 若存在待上屏的字，将当前的首项上屏。

请教，这应该如何实现？非常感谢！

**Comment by DogLooksGood** [comment]
```
(defun rime-commit-and-toggle-input-method ()
  (interactive)
  (when (rime-lib-process-key 32 0)
    (let ((commit (rime-lib-get-commit)))
      (insert commit)
      (rime--clear-state)
      (toggle-input-method))))
```
1. 这个函数必须以 `rime-` 开头，不然 rime 自己就会清空所有的状态。
2. process 32 也就是空格
3. `rime-lib-get-commit` 可以得到要上屏的内容

**Comment by ATNewHope** [comment]
太好了，感谢回复以及详细的解答！时值新年，祝作者新年快乐，万事顺遂！

这个配置在我的 Emacs 上，只能起一半作用：可以从 emacs-rime 切换到取消输入法，但不能从无输入法时切换到 emacs-rime。

所以我对括号稍作调整，亲测有效，完整配置如下：
```elisp
;切输入法时首字自动上屏
;https://github.com/DogLooksGood/emacs-rime/issues/211
(defun rime-commit-and-toggle-input-method ()
  (interactive)
  (when (rime-lib-process-key 32 0)
    (let ((commit (rime-lib-get-commit)))
      (insert commit)
      (rime--clear-state)))
  (toggle-input-method))

(global-set-key (kbd "C-SPC") 'rime-commit-and-toggle-input-method)
(map! "C-SPC" #'rime-commit-and-toggle-input-method)
```
（注：这里的 `map!` 是 Doom Emacs 用于配置键位的宏）

然后就可以用 Ctrl+空格 来切换输入法了，并且若存在待上屏的字则自动上屏。

另外，我认为这是一个很实用的功能（并且也是向 fcitx5-rime 看齐），可否请作者大大把这个函数定义内置在插件中呢？再次感谢！

**Comment by DogLooksGood** [comment]
新年快乐，欢迎提 PR 来支持你的想法。比如加入一个变量来直接控制这个行为。

**Comment by ATNewHope** [comment]
考虑了一下，还是先不放在插件内部了，因为目前可能仍不宜（通过变量决定是否）真正覆盖 `toggle-input-method` 。据我观察，似乎（不确定）第一次开启输入法仍需要 `toggle-input-method` ，而不能是 `rime-commit-and-toggle-input-method` 。

我还是将这个作为自定义方法放在 README 好了。

**Comment by ATNewHope** [comment]
> 考虑了一下，目前可能仍不宜（通过变量决定是否）真正覆盖 `toggle-input-method` 。据我观察，似乎（不确定）第一次开启输入法仍需要 `toggle-input-method` ，而不能是 `rime-commit-and-toggle-input-method` 。
> 
> 我还是将这个作为自定义方法放在 README 好了。
每次启动 Emacs 后须使用 toggle-input-method 才能调用此函数的问题，已经修复。见 #212
