### ISSUE TITLE
[BUG]宫保拼音好像没法用

### ISSUE THREAD

**Issue by nicewise** [DogLooksGood/emacs-rime#235]
**问题描述**

切换成宫保拼音后，打字没反应，朙月拼音或小鹤双拼是正常的

**Emacs中的配置**

```
(use-package rime
  :custom
  (default-input-method "rime")
  :bind
  (:map rime-mode-map
        ("C-`" . 'rime-send-keybinding)))
```

**复现方式**（安装遇到问题时省略）

复现问题所需的操作

**是否可在 emacs -Q 中复现**

否

**截图**

展示错误的截图或动图

**环境信息**

- 操作系统：如 ArchLinux
- Emacs版本：如 29.4
- Librime版本：如 1.11.1
- Librime安装方式：pacman
- 安装方式：Melpa

**Comment by DogLooksGood** [comment]
Emacs 中无法获得按键抬起的事件，并击输入法是通过按键抬起来触发输入的（这样才知道哪些键一起按下了）。
