### ISSUE TITLE
在 i-search 中使用有问题

### ISSUE THREAD

**Issue by Z572** [DogLooksGood/emacs-rime#25]
![在isearch使用](https://user-images.githubusercontent.com/37945516/76971852-c4f30e80-6968-11ea-9ae7-1eb259fa7d0f.gif)

**Comment by DogLooksGood** [comment]
看起来好像没有什么规律啊

**Comment by Z572** [comment]
<kbd> C-s </kbd> <kbd>C-\ </kbd> 输入随便什么 ,  
返回 ``` isearch-with-input-method: Symbol’s function definition is void: nil ``` 
再 <kbd> C-\ </kbd> 才能输入

**Comment by DogLooksGood** [comment]
可以重现

**Comment by Z572** [comment]
https://emacs.stackexchange.com/questions/24274/how-to-use-input-methods-in-minibuffer

isearch 不使用 minibuffer, 需要 <kbd> M-e </kbd> 切换到 minibuffer 来编辑

**Comment by DogLooksGood** [comment]
所以处在一个不知道是哪个buffer，所以变量 input-method 为 nil 的地方？

**Comment by Z572** [comment]
处在搜索的 buffer 中, 在 isearch 切换会改变搜索的 buffer 的输入法

**Comment by DogLooksGood** [comment]
有个变量叫 `isearch-input-method-function` 但是好像设置了没有用。

**Comment by Z572** [comment]
在 isearch 中 切换调用的是 isearch-toggle-input-method
``` elisp
(defun isearch-toggle-input-method ()
  "Toggle input method in interactive search."
  (interactive)
  (let ((overriding-terminal-local-map nil))
    (toggle-input-method))
  (setq isearch-input-method-function input-method-function
	isearch-input-method-local-p t)
  (setq input-method-function nil)
  (isearch-update))
```

**Comment by Z572** [comment]
目前我有个想法, 
让 isearch 启动时自动开启 isearch-edit-string ,
但感觉这样不好

**Comment by DogLooksGood** [comment]
这个函数里面，是不是input-method-function是 nil?

**Comment by DogLooksGood** [comment]
> 目前我有个想法,
> 让 isearch 启动时自动开启 isearch-edit-string ,
> 但感觉这样不好

这样是不好，不应该改变其它东西的行为。

**Comment by Z572** [comment]
这个函数 直接调用  rime-input-method ,直接跳过了 rime-activate

**Comment by DogLooksGood** [comment]
并没有跳过，还是会调用 rime-activate 的

**Comment by Z572** [comment]
> 是不是input-method-function是 nil?

是

**Comment by DogLooksGood** [comment]
有点头绪了
```
(make-variable-buffer-local 'input-method-function)
(make-variable-buffer-local 'deactivate-current-input-method-function)
```
在于这两行他们让这两个函数变成了buffer local的。
所以在 isearch-toggle-input-method 里面就找不到合适的值。

**Comment by Z572** [comment]
用到 isearch-mode-hook ?

**Comment by Z572** [comment]
https://www.gnu.org/software/emacs/manual/html_node/elisp/Creating-Buffer_002dLocal.html#Creating-Buffer_002dLocal
可以参考一下

**Comment by DogLooksGood** [comment]
即使 `isearch-input-method-function` 是正确的，也是会有这个错误

**Comment by Z572** [comment]
或许可以参考一下 emacs 本身自带的中文输入法?

**Comment by Z572** [comment]
``` elisp
(define-minor-mode pyim-isearch-mode
  "这个 mode 为 isearch 添加拼音搜索功能."
  :global t
  :group 'pyim
  :require 'pyim
  :lighter " pyim-isearch"
  (if pyim-isearch-mode
      (progn
        (advice-add 'isearch-search-fun :override #'pyim-isearch-search-fun)
        (message "PYIM: `pyim-isearch-mode' 已经激活，激活后，一些 isearch 扩展包有可能失效。"))
    (advice-remove 'isearch-search-fun #'pyim-isearch-search-fun)))
```
这是 pyim 的 define-minor-mode

**Comment by DogLooksGood** [comment]
> ```emacs-lisp
> (define-minor-mode pyim-isearch-mode
>   "这个 mode 为 isearch 添加拼音搜索功能."
>   :global t
>   :group 'pyim
>   :require 'pyim
>   :lighter " pyim-isearch"
>   (if pyim-isearch-mode
>       (progn
>         (advice-add 'isearch-search-fun :override #'pyim-isearch-search-fun)
>         (message "PYIM: `pyim-isearch-mode' 已经激活，激活后，一些 isearch 扩展包有可能失效。"))
>     (advice-remove 'isearch-search-fun #'pyim-isearch-search-fun)))
> ```
> 
> 这是 pyim 的 define-minor-mode

这个看起来不是在 isearch 里面用输入法，只是在里面用输入法的逻辑搜索？

**Comment by Z572** [comment]
好像是的

**Comment by DogLooksGood** [comment]
知道原因了，是
`rime--init-minibuffer`
里面会 deactivate 导致的。

感觉 minibuffer 这里有不少的处理还有问题
