### ISSUE TITLE
请问 pyim 还有 liberime-config 这两个 package 都不用了吗？

### ISSUE THREAD

**Issue by lyserenity** [DogLooksGood/emacs-rime#26]
如题

**Comment by DogLooksGood** [comment]
emacs-rime 直接依赖 librime，不再依赖其它的 elisp 包了。

**Comment by lyserenity** [comment]
``rime--load-dynamic-module: Failed to compile dynamic module``

抱歉，我昨天和今天试了一直是这信息，但是我也照教程写了，还有可能是哪里有问题呢？

p.s. 我用 spacemacs，设定如下：
```
(rime :location (recipe :fetcher github
                                  :repo "DogLooksGood/emacs-rime"
                                  :files ("rime.el")))

(defun XXXX/init-rime ()
  (use-package rime
    :init
    :custom
    (rime-librime-root "~/.emacs.d/librime/dist")
    (default-input-method "rime")
    ))
```

**Comment by DogLooksGood** [comment]
@lyserenity `:files` 里面需要  rime.el, Makefile 和 lib.c

**Comment by DogLooksGood** [comment]
我应该更新下文档，这个文档是给 melpa 之后用的，但是目前还没有在melpa上面。

**Comment by lyserenity** [comment]
```
          (rime :location (recipe :fetcher github
                                  :repo "DogLooksGood/emacs-rime"
                                  :files ("rime.el" "Makefile" "lib.c")))
```
我改了还是一样.....

**Comment by Z572** [comment]
pull 一下

**Comment by lyserenity** [comment]
> pull 一下
> 昨天有一个 bug 会导致无法编译

我已经更到最新了，还是一下，会不会是哪里设定有问题，还是我 emacs 编译的版本的问题？

**Comment by Z572** [comment]
把 ```(rime-librime-root "~/.emacs.d/librime/dist") ``` 去掉试试

**Comment by lyserenity** [comment]
> 把 `(rime-librime-root "~/.emacs.d/librime/dist") ` 去掉试试

还是一样的 message ，我还有什么可以尝试或测试的吗？谢谢

**Comment by Z572** [comment]
删掉之后 重新 git clone

**Comment by DogLooksGood** [comment]
@lyserenity 如果更新了的话，你在插件的那个目录里面应该可以看到 lib.c Makefile这两个文件，这种情况下make就不会有那个错了。

**Comment by lyserenity** [comment]
```
1 error generated.
make: *** [lib] Error 1
rime-compile-module: Compile Rime dynamic module failed
Mark set
gcc -fPIC -g -shared -lrime lib.c -o librime-emacs.so
lib.c:23:10: fatal error: 'rime_api.h' file not found
#include <rime_api.h>
         ^
1 error generated.
make: *** [lib] Error 1
rime-compile-module: Compile Rime dynamic module failed
```
另外，目录里也有 lib.c Makefile 文件
![image](https://user-images.githubusercontent.com/32646062/77045616-860e9880-69fc-11ea-9ca7-427f445bd436.png)

**Comment by Z572** [comment]
你 librime 没装吗?

**Comment by DogLooksGood** [comment]
@lyserenity 如果是Mac上面的话，比较好的办法就是先下载个 librime 

https://github.com/DogLooksGood/emacs-rime/blob/master/README_CN.org#macos

因为 Mac 里面一般情况下，系统路径里面没有 librime 能编译的时候直接拿来用。

**Comment by lyserenity** [comment]
> @lyserenity 如果是Mac上面的话，比较好的办法就是先下载个 librime
> 
> https://github.com/DogLooksGood/emacs-rime/blob/master/README_CN.org#macos
> 
> 因为 Mac 里面一般情况下，系统路径里面没有 librime 能编译的时候直接拿来用。

![image](https://user-images.githubusercontent.com/32646062/77063121-21613700-6a18-11ea-8029-8c88b7c6aa04.png)
是说这步骤吗？我一直都有照作，但 message 还是一样.....

**Comment by DogLooksGood** [comment]
在package的目录下
```
LIBRIME_ROOT=~/.emacs.d/librime/dist/ make lib
```
如果配置正确的话，这个是用来构建的命令

需要检查的东西就是存在 `~/.emacs.d/librime/dist/lib/librime.dylib`和`~/.emacs.d/librime/dist/include/rime_api.h`

如果找不到 rime_api.h 的话应该是传进来的 LIBRIME_ROOT 不对。

`LIBRIME_ROOT=~/.emacs.d/librime/dist/ make lib -n` 可以查看展开后的 make 指令

**Comment by lyserenity** [comment]
可以了.....谢谢大佬们
