### ISSUE TITLE
posframe: 候选显示不完全

### ISSUE THREAD

**Issue by lyserenity** [DogLooksGood/emacs-rime#35]
![image](https://user-images.githubusercontent.com/32646062/77151190-6779d180-6ad0-11ea-9e56-5237916d4f18.png)
候选的字下半部不见，请问怎么办？谢谢

**Comment by DogLooksGood** [comment]
看起来像是使用了中英文高度不同的字体导致posframe高度计算的错误？

可以尝试使用单行候选
```
(setq rime-posframe-style 'simple)
```

或使用等高的字体。

**Comment by lyserenity** [comment]
原来如此，我习惯中文字体比英文大一字号，没想到是这原因，感谢

**Comment by DogLooksGood** [comment]
我想知道在你这种情况下，全角空格是不是有和中文一样的高度。
如果是的话，上面第一行的结尾，也许我们可以加一个全角空格。

`rime--candidate-prefix-char` 函数中的 `\n` 换成 `\n全角空格`. 
也许能让posframe获得正确的高度。

**Comment by lyserenity** [comment]
我不知道怎么判断....
![image](https://user-images.githubusercontent.com/32646062/77155729-ed9a1600-6ad8-11ea-9964-859e657c73b3.png)
这样可以吗？

**Comment by DogLooksGood** [comment]
就是原本一行只有英文字符，加入一个全角空格的时候，会把行高拉高吗？

**Comment by lyserenity** [comment]
![2020-03-20 22-42-23 2020-03-20 22_46_07](https://user-images.githubusercontent.com/32646062/77175206-2f3cb800-6afd-11ea-95fd-dfef72b23aba.gif)
如果就是 gif 中呈现的样子的话，那应该就是行拉高了（我在 aaaa 后贴上全角空格）

**Comment by lyserenity** [comment]
``rime-posframe-properties`` 如果加上 ``:font`` 的设定，候选就不会被切掉了

**Comment by DogLooksGood** [comment]
这个只能看用户的设置了，毕竟默认用什么 font 都不合适。
