### ISSUE TITLE
基于inline ascii模式的自动中英文

### ISSUE THREAD

**Issue by DogLooksGood** [DogLooksGood/emacs-rime#40]
![switch](https://user-images.githubusercontent.com/11796018/77205232-6461fe00-6b2f-11ea-8909-7fabaa0891dd.gif)

能处理自动英文中包含空格的情况。

**Comment by DogLooksGood** [comment]
#41 提供了比较基础的实现

**Comment by Z572** [comment]
在 inline ascii 模式下是不是应该隐藏 posframe 比较好？

**Comment by DogLooksGood** [comment]
是个，我觉得可以这样处理。

**Comment by DogLooksGood** [comment]
posframe 自动隐藏的功能会导致 posframe 没有时功能不正常

**Comment by Z572** [comment]
好吧

**Comment by DogLooksGood** [comment]
#41 已实现
