### ISSUE TITLE
说明文档中ubuntu 使用librime-dev的说法有误

### ISSUE THREAD

**Issue by cloudqq** [DogLooksGood/emacs-rime#42]
![image](https://user-images.githubusercontent.com/249553/77246366-69bf6580-6c61-11ea-8af9-69dbbcaa6fa5.png)

检查了下发现librime-dev 按装的版本是1.2.9 与当前最新的librime 差异很大

![image](https://user-images.githubusercontent.com/249553/77246385-8c517e80-6c61-11ea-9e05-73c3a495e5c6.png)

**Comment by DogLooksGood** [comment]
ubuntu里面是不是不同的系统版本用的不同的源？librime当前版本好像是1.5.3，这个版本差的有点多。

不追究这个问题的话，可以自己构建librime。如果使用自己构建的方式，要在elisp配置rime-librime-root。值参照readme中installation节的最后

**Comment by DogLooksGood** [comment]
讨论合并到 #43
