### ISSUE TITLE
Compilation errors on Ubuntu

### ISSUE THREAD

**Issue by llcc** [DogLooksGood/emacs-rime#43]
1 首次安装编译时，会出现以下的编译错误。

```
gcc -fPIC -O2 -Wall -shared -lrime lib.c -o librime-emacs.so
lib.c:24:10: fatal error: rime_api.h: No such file or directory
   24 | #include <rime_api.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:25: lib] Error 1
```

2 首先怀疑应该是系统中没有librime包。通过搜索包管理，安装`librime-dev`包后重新编译，显示编译成功。但是切换输入法到rime时，emacs直接被杀掉，后台信息：

```
emacs: symbol lookup error: /home/leizhe/Emacs/.emacs.d/elpa/rime-20200321.2331/librime-emacs.so: undefined symbol: rime_get_api
```
是不是包安装有什么问题？

**Comment by Z572** [comment]
我不用 ubuntu, 应该是librime-dev 太旧了, 需要下载更新的
或从源码安装 https://github.com/rime/librime

**Comment by cloudqq** [comment]
我在ubuntu下用librime自行编译的版本也会遭遇到楼上一样的问题，并且深陷泥潭无法自拔

**Comment by Z572** [comment]
> 注意：如果您使用的是MacOS或标准路径中没有库，则必须指定 rime-librime-root

**Comment by llcc** [comment]
fcitx-rime官方文档里面说依赖librime-devel，但是`fcitx-rime`时似乎并没有按照合适的librime版本。自行编译的话也是各种坑，成功几率很低。

**Comment by DogLooksGood** [comment]
应该更新一个文档来说明 ubuntu 上面 librime-dev 的版本比较旧。

因为 librime 没有提供 Linux 上面的 Release
https://github.com/rime/librime/releases

所以只能通过源码编译，在 librime 完成编译之后。在 elisp 的配置中指定 rime-librime-root，可以由 emacs-rime 自动完成 dynamic module 的编译环境。

**Comment by DogLooksGood** [comment]
目前 librime-devel 的版本是多少？

**Comment by llcc** [comment]
![image](https://user-images.githubusercontent.com/3996879/77249390-1c082480-6c84-11ea-9416-b4c420240088.png)

**Comment by DogLooksGood** [comment]
麻烦贴一下 emacs lisp 中的配置，和 lib 的路径。我猜测在 /usr/lib/librime.so 和 /usr/include/rime_api.h

**Comment by llcc** [comment]
Emacs中的配置：
```lisp
(use-package rime
     :quelpa (rime
              :fetcher github
              :repo "DogLooksGood/emacs-rime"
              :files ("rime.el" "Makefile" "lib.c"))
     :custom (default-input-method "rime"))
```

lib的路径：
```
/usr/include/rime_api.h
/usr/lib/librime.so: No such file or directory
```

**Comment by DogLooksGood** [comment]
/usr/lib/librime.so 这个目录文件没有应该是问题所在。

emacs-rime 启动的时候找不到 librime 就有这样的问题。
可能需要找一下这个文件安装librime-devel的时候被放在哪里了。

**Comment by cloudqq** [comment]
离成功不远了。

![image](https://user-images.githubusercontent.com/249553/77249923-7b176a80-6c7f-11ea-82b0-c89b223439fb.png)

**Comment by Z572** [comment]
``` shell
ls /usr/lib/librime*
```
试一下

**Comment by DogLooksGood** [comment]
@cloudqq  可否总结一下，我觉得readme中关于ubuntu的说明可能需要更新。

**Comment by llcc** [comment]
很奇怪，usr目录下并不存在任何librime文件。应该是安装不完全吧，但是不太清
楚什么原因。

**Comment by DogLooksGood** [comment]
`dpkg -L librime-devel`

**Comment by Z572** [comment]
` ls /usr/local/lib/librime* `

**Comment by llcc** [comment]
`dpkg -L librime-devel` produces
```
pkg-query: package 'librime-devel' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
```

显示并未安装，然后我执行安装，提示我管理器里面并没有此包。

**Comment by Z572** [comment]
应该 ` dpkg -L librime-dev ` 吧?

**Comment by llcc** [comment]
谢谢，执行的结果是：

```
/.
/usr
/usr/include
/usr/include/rime_api.h
/usr/include/rime_levers_api.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/rime.pc
/usr/share
/usr/share/cmake
/usr/share/cmake/rime
/usr/share/cmake/rime/RimeConfig.cmake
/usr/share/doc
/usr/share/doc/librime-dev
/usr/share/doc/librime-dev/README.md.gz
/usr/share/doc/librime-dev/copyright
/usr/lib/x86_64-linux-gnu/librime.so
/usr/share/doc/librime-dev/CHANGELOG.md.gz
/usr/share/doc/librime-dev/changelog.Debian.gz
```

**Comment by Z572** [comment]
设置 `export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ `

**Comment by cloudqq** [comment]
1. Ubuntu下需要安装最新版的librime 1.5.3 必须下载源代码方式来安装， 系统发现的Librime-dev 版本太旧只有1.2.9
2. 需要成功安装librime 则又必须线安装opencc,也需要源代码方式安装
3. 当前Makefile 中在Ubuntu下编译出的so有问题， 需要将-lrime 的开关项放到最后才能得到可用的so

看下两种方式下编译出的so的差异， 在dynamic section 段
![image](https://user-images.githubusercontent.com/249553/77250556-bd42ab00-6c83-11ea-904c-85ba4b8f299e.png)

![image](https://user-images.githubusercontent.com/249553/77250549-b5830680-6c83-11ea-959e-4aa0b34aaebe.png)


以下是我编译librime的方式，请参考

`
apt-get install doxygen  python-gi python3-gi python-xlib \
libboost-dev libboost-filesystem-dev libboost-regex-dev libboost-system-dev libboost-locale-dev libgoogle-glog-dev libgtest-dev

git clone https://github.com/BYVoid/OpenCC.git
cd OpenCC/
make
make install

cd /usr/src/gtest
cmake CMakeLists.txt
make
#copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder
cp *.a /usr/lib

git clone https://github.com/rime/librime.git
cd librime/
make
make install

rime_dir=/usr/local/share/rime
curl -fsSL https://git.io/rime-install | bash
apt-get install sudo


`

**Comment by DogLooksGood** [comment]
https://stackoverflow.com/questions/8207464/linking-math-library-in-gcc-4-6-1-ubuntu-11-10/8209036#8209036

参数顺序是因为这个原因？

**Comment by llcc** [comment]
万分感谢。按照你的script我应该是成功安装rime了。
但是编译时仍然会出现刚开始的错误。
我顺便更新下刚才的调取命令的结果；

dpkg -L librime-dev
/.
/usr
/usr/include
/usr/include/rime_api.h
/usr/include/rime_levers_api.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/rime.pc
/usr/share
/usr/share/cmake
/usr/share/cmake/rime
/usr/share/cmake/rime/RimeConfig.cmake
/usr/share/doc
/usr/share/doc/librime-dev
/usr/share/doc/librime-dev/README.md.gz
/usr/share/doc/librime-dev/copyright
/usr/lib/x86_64-linux-gnu/librime.so
/usr/share/doc/librime-dev/CHANGELOG.md.gz
/usr/share/doc/librime-dev/changelog.Debian.gz

**Comment by DogLooksGood** [comment]
如果你的librime成功编译了，比如放在 ~/.emacs.d/librime

那么可以设置 rime-librime-root 为 ~/.emacs.d/librime/dist 

启动输入法应该就可以自动完成剩下的。

**Comment by DogLooksGood** [comment]
刚才试了下 librime 自带的 dockerfile 可以构建成功。不知道这个能不能拿来用。

**Comment by wsw0108** [comment]
Ubuntu里面，`librime-dev`只是librime开发包吧，应该还有个包叫`librime`，是运行时需要的。

`rime_get_api`从librime的源码来看，是1.0就已经添加的，除非版本到2.0，这个api应该不会变。

既然安装`librime-dev`后编译成功，可以运行
```
ldd librime-emacs.so
```
看看依赖是否完整。

**Comment by wsw0108** [comment]
http://mirrors.163.com/ubuntu/pool/universe/libr/librime/

**Comment by DogLooksGood** [comment]
这里面看起来有1.5.3的版本的，为什么apt找不到？

**Comment by wsw0108** [comment]
> 这里面看起来有1.5.3的版本的，为什么apt找不到？

可能和ubuntu版本有关，各种代号，bionic/xenial之类

**Comment by SuperMMX** [comment]
> 是不是 -lrime 只要在 lib.c 后面就可以。

Debian sid 下成功，只把 -lrime 放到最后就对了，否则出现 rime_get_api 没找到的错误。 librime 版本为 1.5.3.

**Comment by DogLooksGood** [comment]
2cc9006d8eb2a2ef5bf3bdbd64f6d2b46faf20e9
提交更新了gcc的命令顺序。

**Comment by llcc** [comment]
今天重新安装了下rime，可以正常运行了。输入体验很愉快。

仅通过`apt-get install ibus-rime`安装依赖包是不够的，ibus-rime只会安装librime-bin，librime-data和librime1等包。
还是需要`apt-get install librime-dev`来正确安装包，目前安装版本为官方最新版本1.5.3。

PS：最好不要自己compile，compile时有时会更新某些包，某些包的最新版本会有bug。

**Comment by DogLooksGood** [comment]
如有问题可以再打开issue
