### ISSUE TITLE
macOS上 似乎需要生成 .dylib 而不是so文件

### ISSUE THREAD

**Issue by jixiuf** [DogLooksGood/emacs-rime#45]
``` 
module-file-suffix
```
```
".dylib"
```
另外最好将 .dylib 也加到gitignore里。

**Comment by DogLooksGood** [comment]
是不是 Mac 的多个版本有的是 .so 有的是 .dylib？

**Comment by jixiuf** [comment]
亿乎是这样， 我记得以前也是so的 ，不知道是升了emacs 还是升了macos 才这样的 。建议macos上建个软链接。

**Comment by DogLooksGood** [comment]
嗯，我们可以选择写死 .so，在 Makefile 也是生成 .so 就好了。

**Comment by DogLooksGood** [comment]
dynamic module和package本身是强相关的，没有明确的去适配多个名字的必要。
