### ISSUE TITLE
lib.c:24:10: fatal error: 'rime_api.h' file not found

### ISSUE THREAD

**Issue by lyserenity** [DogLooksGood/emacs-rime#58]
我从 emacs-china 来的，我有点不确定你最后的意思，是说图中的状况要开 issue 吗？如果开错了再麻烦关掉，谢谢
![image](https://user-images.githubusercontent.com/32646062/77540422-055d0a00-6ede-11ea-8930-6e0caa947dda.png)

**Comment by DogLooksGood** [comment]
遇到问题总是可以开一个issue，没有什么问题。

我先补充一些信息。

构建的错误
```
env C_INCLUDE_PATH=~/.emacs.d/librime/dist/include/ gcc lib.c -o librime-emacs.so -fPIC -O2 -Wall -shared -L ~/.emacs.d/librime/dist/lib/ -Wl,-rpath ~/.emacs.d/librime/dist/lib/ -lrime
lib.c:24:10: fatal error: 'rime_api.h' file not found
#include <rime_api.h>
         ^
1 error generated.
```

相关的配置
```
    :custom
    (rime-librime-root "~/.emacs.d/librime/dist")
    (default-input-method "rime")
```

**Comment by cnsunyour** [comment]
你手动把那条编译命令的相对目录改成绝对目录试试

**Comment by DogLooksGood** [comment]
确实某个PR之后expand-file-name就去掉了，这可能是个问题。

**Comment by cnsunyour** [comment]
@DogLooksGood 有可能，因为在 emacs 里没有shell 的 env 变量，所以可能判断不出 ~ 是哪个目录

**Comment by lyserenity** [comment]
可以了，我先试了 emacs-china 上的建议
``(rime-librime-root (expand-file-name "librime/dist" user-emacs-directory))``
这样就没问题了（有需要关掉这 issue 的话，再麻烦大佬们帮关，谢谢）

**Comment by DogLooksGood** [comment]
@lyserenity 麻烦更新一次再试一下，提交了这个修复。

**Comment by lyserenity** [comment]
更新之后没问题了，感谢
