### ISSUE TITLE
如何直接使用 use-package 安装？

### ISSUE THREAD

**Issue by QIanGua** [DogLooksGood/emacs-rime#59]
由于没有安装 straight.el, 那么该怎么安装 emacs-rime 呢？

**Comment by Z572** [comment]
下载下来 在 `use-package` 里用 `:load-path "path/to/rime"`

**Comment by QIanGua** [comment]
Thanks，搞定了。原来位置是和以前 clone 的librime 位置搞混了

**Comment by DogLooksGood** [comment]
当前版本已可以直接通过 melpa 安装，不需要 straight 或 quelpa
