### ISSUE TITLE
rime-mode-map优先级问题

### ISSUE THREAD

**Issue by DogLooksGood** [DogLooksGood/emacs-rime#6]
似乎需要确保 rime-mode-map 总有最高的优先级。

可能有用的内容：
http://ergoemacs.org/emacs/minor_mode_key_priority.html

https://emacs.stackexchange.com/questions/13447/how-to-set-a-rule-for-the-order-of-minor-mode-map-alist

**Comment by DogLooksGood** [comment]
@Z572 

http://ergoemacs.org/emacs/minor_mode_key_priority.html

里面提供了一种方式来查看各minor-mode-map的优先级。

**Comment by Z572** [comment]
现在rime和paredit好像不会有冲突了,很奇怪,不过谢谢了

**Comment by Z572** [comment]
输入法应该设置 overriding-local-map 来保证优先级别

**Comment by DogLooksGood** [comment]
其实你可以直接 reopen

mode的加载的先后顺序似乎是有关系的，后加载的有更高的优先级。
backspace和输入法的实现没有关系，输入法不处理 127 (DEL)

**Comment by Z572** [comment]
> Keymap that replaces (overrides) local keymaps.
If this variable is non-nil, Emacs looks up key bindings in this
keymap INSTEAD OF the keymap char property, minor mode maps, and the
buffer's local map.  Hence, the only active keymaps would be
overriding-terminal-local-map, this keymap, and global-keymap, in
order of precedence.

**Comment by Z572** [comment]
![image](https://user-images.githubusercontent.com/37945516/77081044-07821d00-6a35-11ea-8dc6-1d087d226d7e.png)

**Comment by DogLooksGood** [comment]
#31
