### ISSUE TITLE
compilation on windows x64

### ISSUE THREAD

**Issue by Jiffies-Duke** [DogLooksGood/emacs-rime#64]
I have managed to compile the code successfully under windows 10 x64 platform by using tdm64-gcc :
 
`cd /path/to/librime/dist/lib/`

`ren rime.lib rime.a`

`gcc lib.c -m32 -shared -o librime-emacs.dll -I/path/to/librime/dist/include -I/path/to/emacs_src/src -L/path/to/librime/dist/lib -Wl,-rpath /path/to/librime/dist/lib/ -lrime`

After that, copy the generated dll to emacs-rime package, start emacs, press C-| ......
There is an error message says "load-file: Module could not be opened: librime-emacs.dll is not a valid win32 program.
Emacs version is 27.0.50 x86_64.
May anybody take a test to verify the compilation and if it is related to architecture(x86, x86_64)?

**Comment by DogLooksGood** [comment]
Hi, I'm not familiar with Windows. AFAIK the Windows emacs is compiled on msys2, so you have to compile librime in msys2 too. You can't use the release, that is compiled with VC.

**Comment by Jiffies-Duke** [comment]
I googled and found that a 64-bit process cannot load a 32-bit module into its process space.
By either making a 64-bit wrapper dll which delegates calls to the 32-bit DLL running in a surrogate process, or compiling librime to a 64-bit dll would solve the issue.
By the way, the compiled dll works well on a 32-bit win7 and 32-bit emacs.

**Comment by Jiffies-Duke** [comment]
我已经解决了windows 10 x64下使用emacs-rime的问题。方法如下：

1. 编译 librime.dll
在 Windows 平台，RIME 提供的 librime 是 32 位的，只能作为单独的进程在 64 位平台下使用。
如果 Emacs 是 64 位的，则动态模块也必须是 64 位，调用的其他 DLL 也必须是 64 位的。
编译 librime 按官方文档比较复杂，此处参照 https://github.com/merrickluo/liberime/blob/master/msys2-build.sh 中进行。
需要 MSYS2 及其下的 mingw64 环境，相关编译链等。脚本中会自动安装。
依次编译安装 leveldb, marisa, opencc 等后，即可编译 librime。生成的 dll 约 29M，可以 strip 减小到 5M。
按librime官方文档简单测试通过即可。
需要以下文件：librime.dll, rime_api.h, rime_levers_api.h （用于编译本项目）
以及以下文件： opencc 全部, 各种输入法方案 yaml 文件（可从其他地方复制，也可由上述脚本下载，作为rime-data） 

2. 编译 librime-emacs.dll
源代码简单到只有一个 lib.c，但 Makefile 仅能用于其他平台，需要修改。也可以直接gcc：
先将 librime.dll rime_levers_api.h rime_api.h 复制到项目下，
 `gcc lib.c -o librime-emacs.dll -O2 -shared -I. -I/path/to/emacs/include -L. -llibrime` 
编译如果报错，一般是某个.h文件未找到，加上-I路径即可；librime.dll找不到，在-L后面加上路径即可。

3. 复制依赖文件
生成 librime-emacs.dll 后，用 ldd.exe 查看一下依赖的 dll，将 mingw 相关的 dll 全部复制到系统环境变量 PATH 中的某一个路径下。有3个：libwinpthread-1.dll, libstdc++-6.dll, libgcc_s_seh-1.dll，再加librime.dll共4个。也可以将保存这4个文件的文件夹加入PATH变量。否则将无法加载模块。
然后将 opencc 文件夹以及输入法 yaml 等文件放到 rime-data 文件夹，路径在.emacs 配置文件中指定。

4. 修改.emacs 配置文件
增加一段（当然也可以按照官方文档那样用quelpa或straight）：
(use-package rime
  :load-path "~/.emacs.d/rime"
  :custom
  (default-input-method "rime")
  (rime-user-data-dir "~/.emacs.d/rime-user-data")
  (rime-share-data-dir "~/.emacs.d/rime-data")
  (rime-show-candidate 'posframe))
其中 load-path 是本项目文件路径，rime-user-data-dir 是用户的 rime-data。
rime-share-data-dir 是系统 rime-data，必须设置。（rime.el 中未对 windows 平台设初值，不设会报错）

5. 启动emacs
按切换输入法键C-\，第一次需要等rime配置和部署输入法，会卡住10-30秒。看minibuffer显示loading ........ done; Rime activate. （应该是 Rime activated 吧？）即表明成功。

6. 相关文件（64位）
librime.dll 如果不想自己编译，可以从上述 merrickluo/liberime 处下载，需要的4个dll都在其中了。
librime-emacs.dll 我上传一个供试用。
 [librime-emacs.zip](https://github.com/DogLooksGood/emacs-rime/files/4397052/librime-emacs.zip)

其他设置看官方文档。
请@DogLookGood 看一下是否有帮助。

**Comment by DogLooksGood** [comment]
非常感谢，帮了大忙了。

有一个疑问就是第三步的环节，那些 dll 是原本 emacs 当中找不到的吗？

**Comment by Jiffies-Duke** [comment]
那几个libstdc++-6.dll等，都不是emacs中的，是在msys2/mingw64中的。这几个文件的具体位置可以通过ldd.exe librime.dll 查看到。
我检查了官方emacs27.0.50的with-deps中没有，自己编译的emacs27中也没有。
没有试过将这几个dll复制到emacs/bin中是否有效。目前只试过放在librime-emacs.dll 同一目录中无效。

**Comment by Jiffies-Duke** [comment]
刚才又检查了一下，官方 emacs.27.0.50 with-deps 里有 libwinpthread-1.dll, libgcc_s_seh-1.dll, libstdc++-6.dll。但我中午用这个版测试的时候报错，无法加载模块（librime.dll 和 librime-emacs.dll 放在一起）。后来将这四个文件复制到PATH才成功。也许只需要复制 librime.dll 到 emacs/bin 就好了？

**Comment by Jiffies-Duke** [comment]
试过了。只需要将 librime.dll 复制到 emacs/bin 下，和那一堆原本的 dll 放到一起就行了。
注意的是 emacs 官方下载有两个版本，一个是 no-deps 的，里面可能缺少某个 dll；另一个体积大的是带有依赖库的。
这样的话，只需要做两步：复制 librime.dll 到 emacs/bin；修改 Makefile 使之能够在 Windows 下编译。编译器可以用 tdm64-gcc。

**Comment by DogLooksGood** [comment]
gcc编译的时候可以使用 rpath ，这样可以让 librime 在任意位置应该。

类似 MacOS 上面的方式。

**Comment by DogLooksGood** [comment]
从 rime.el 中构建出来的命令和实际需要的构建命令差别在哪里？

**Comment by Jiffies-Duke** [comment]
rime.el 我没做修改，如果是问这个的话。
另外，如果能够在 rime.el 中加上对win平台下 rime-share-data 的默认值，就可以避免未自己定义时加载模块报错。

**Comment by Jiffies-Duke** [comment]
rpath 无效。我被这个坑了好久，一直编译成功，却无法加载。
原因是 tdm64-gcc 以及 mingw64 下 pacman 安装的 gcc 都默认 ./configure --disable-rpath。

**Comment by DogLooksGood** [comment]
> rime.el 我没做修改，如果是问这个的话。
Makefile 里面的默认的 make lib 的命令和实际能构建成功的需要的命令差别在哪里？如果知道区别的话，我就知道怎么对应的改 Makefile 了。或者是脱离现在的 Makefile, 从 liberime 的那个脚本中改出一个能给 emacs-rime 使用的版本。

还有，win 下面的 rime-share-data 应该是在什么位置？

**Comment by Jiffies-Duke** [comment]
修改 Makefile 就可以了，命令的区别不在 rime.el 中。上面的 gcc 命令可以编译成功，也就可以依照命令参数修改 Makefile 了。我明天整理一下，把我的 Makefile 发上来。
liberime 那个脚本使用的是 cmake，对本项目来说有点重了。
win 下面的 rime-share-data 就是在第 2 步编译完 librime 之后，将 opencc 以及 rime 输入法方案的 yaml 文件集中到的地方。可以自定义。我是放在了 `~/.emacs.d/rime-data` 中，然后在 emacs 配置文件中 :custom 下`(rime-share-data-dir` "~/.emacs.d/rime-data")`。
没有这个值的设定在加载模块时会报 stringp, nil，设定在没有 yaml 文件的地方会没有输入法方案。
如果系统中已经安装了 rime 输入法，那么 user-share-data-dir 是在
    【中州韵】 /usr/share/rime-data/
    【小狼毫】 "安装目录\data"
    【鼠鬚管】 "/Library/Input Methods/Squirrel.app/Contents/SharedSupport/"
但最好不要和系统中的 rime 共用。因为编译器不同，生成的 opencc 格式不同。

**Comment by DogLooksGood** [comment]
这个 "安装目录\data" 有点难办啊，你是说再来一个专用的 share-data-dir？那不是改一次配置要改两个地方。

**Comment by Jiffies-Duke** [comment]
最初我是直接用 gcc 命令编译生成 librime-emacs.dll 的，生成之后就不用管 rime.el 自动构建的事了。只需要将几个 dll 放在合适位置即可正常使用；
后来考虑到迁移到其他机器上也能使用，就做了一个简单 Makefile，见最后注释部分；
今天合并了一下，测试成功。
我的 Makefile 如下，请斧正：

``` 
ifdef MODULE_FILE_SUFFIX
	SUFFIX = $(MODULE_FILE_SUFFIX)
else
	SUFFIX = .so
endif
# windows 下，$(MODULE_FILE_SUFFIX) 是 .dll
# 不通过 emacs 调用，SUFFIX 是 .so，可以改名为 .dll 正常使用

TARGET       = librime-emacs$(SUFFIX)

CC           = gcc

CFLAGS   = -fPIC -O2 -Wall

ifeq ($(SUFFIX), .dylib)
	LDFLAGS = -dynamiclib
else
	LDFLAGS = -shared
endif

# windows 下编译 librime 生成的是 librime.dll，所以是 -llibrime， 不是 -lrime
# 也可以将 librime.dll 改名为 rime.dll，这里就不用改了
ifdef LIBRIME_ROOT
	CFLAGS  += -I ${LIBRIME_ROOT}include/
	LDFLAGS  += -L ${LIBRIME_ROOT}lib/ -Wl,-rpath ${LIBRIME_ROOT}lib/ -llibrime
else
	LDFLAGS  += -llibrime
endif

# EMACS_MODULE_HEADER_ROOT 没有定义
# 需要在 init.el 中:custom 下定义 rime-emacs-module-header-root
# 指向 emacs-module.h
ifdef EMACS_MODULE_HEADER_ROOT
	CFLAGS += -I ${EMACS_MODULE_HEADER_ROOT}
endif

default: clean test

clean:
	-rm $(TARGET)

lib:
	$(CC) lib.c -o $(TARGET) $(CFLAGS) $(LDFLAGS)

test:
	emacs -q test.el -e eval-buffer

## 最简 Makefile 如下：
## 需要预先将 .h .dll 复制至本目录下
## 编译完成后可只保留 rime.el, librime-emacs.dll
## librime.dll 移动到 emacs/bin 下，即可。
# TARGET = librime-emacs.dll
# CC = gcc
# CFLAGS = -I.
# LDFLAGS = -shared -L. -llibrime
# lib:
#	$(CC) lib.c -o $(TARGET) $(CFLAGS) $(LDFLAGS)

```

需要注意的有：
1. 在 :custom 下需要定义 rime-librime-root, rime-emacs-module-header-root
2. 在 rime.el 中 `(shell-command (format "cd %s ; env %s make lib" rime--root env))` 那个`;`无法在 windows 下使用，会报“找不到指定的路径”，需要改成` && `
3. 某些情况下上面2的 cd %s 会不成功，仍然停留在 emacs/bin，找不到Makefile，会报“无法找到编译目标 lib”。此时用 C-x C-f 打开这个目录下的文件，如 Makefile, 或 rime.el，再按 C-\ 调用编译，即可成功。

至于 share-data-dir，可以先预设在 c:/program files(x86)/rime/data，有需要的会自行在 :custom 中重新设置。自己配置的输入法文件在 user-data-dir 中，不会影响前者。

**Comment by Jiffies-Duke** [comment]
![图片](https://user-images.githubusercontent.com/19168838/77843043-ca075780-71cb-11ea-9a73-218771d2c8c3.png)

**Comment by DogLooksGood** [comment]
比如 Linux 上，对于 librime 就应该是 -lrime 啊， msys2 上面这里是有区别的吗？

**Comment by Jiffies-Duke** [comment]
> 比如 Linux 上，对于 librime 就应该是 -lrime 啊， msys2 上面这里是有区别的吗？
windows 下 `gcc  -lrime `会去找一个名为 rime.dll  的文件，而不是 librime.dll。找不到就会报 
`cannot find -lrime`

**Comment by DogLooksGood** [comment]
关于 librime 的构建，有没有完整可用的脚本？

**Comment by Jiffies-Duke** [comment]
完全可以用上面的这个脚本：
https://github.com/merrickluo/liberime/blob/master/msys2-build.sh
略作修改，去掉构建 liberime 包、zip 的时候重新组织一下路径和文件，做成像 librime-osx 那种结构就可以了。甚至不用修改，从生成的 zip 里（ https://github.com/merrickluo/liberime/releases/download/v0.0.3/liberime-v0.0.3-windows-x86_64.zip ）抽出需要的那几个文件就好了。
我个人更建议直接给构建好了的windows包，把 librime.dll 甚至 librime-emacs.dll 直接给用户，不用再编译了。可以分 win32 （这个 librime 官方有）、win64 两个 release。这对不想折腾，开箱即用的人来说非常方便。
对于想自己编译的用户，整理上文，形成文档，自行折腾，乐在其中。

**Comment by tumashu** [comment]
我想将 librime 提交到 msys2 仓库中， 现在大的框架已经搭建完成，只是对 shellscript 不太熟悉，需要进一步打磨，有兴趣的小伙伴一块研究研究啊 

https://github.com/msys2/MINGW-packages/pull/6347

librime 提交到 msys2 之后， 编译的问题也就解决了一大半

**Comment by tumashu** [comment]
提交成功，pacman -Ss rime 试试

**Comment by tumashu** [comment]
window 下，不需要上面那么折腾了， @DogLooksGood 你可以给 https://github.com/msys2/MINGW-packages 提报一个 emacs-rime 的包，类似下面，到时候直接用 msys2 pacman 安装就完事了。
```
# Maintainer: Feng Shu <tumashu@163.com>

_realname=liberime
pkgbase=mingw-w64-${_realname}
pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
pkgver=0.0.5
pkgrel=2
pkgdesc="An emacs dynamic module provide librime bindings for emacs (mingw-w64)"
arch=('any')
url="https://github.com/merrickluo/liberime"
license=('GPL3')
depends=("${MINGW_PACKAGE_PREFIX}-librime")
makedepends=("${MINGW_PACKAGE_PREFIX}-gcc"
             "${MINGW_PACKAGE_PREFIX}-cmake")
# checkdepends=("${MINGW_PACKAGE_PREFIX}-gtest")
source=("${_realname}-${pkgver}.tar.gz::https://github.com/merrickluo/liberime/archive/v${pkgver}.tar.gz")
sha256sums=('0430402c5959df603a56df259787befa5e687ca95520c1c2e8ff7b84a2f832eb')

prepare() {
   cd "${_realname}-${pkgver}"
}

build() {
  if check_option "debug" "n"; then
    extra_config+=("-DCMAKE_BUILD_TYPE=Release")
  else
    extra_config+=("-DCMAKE_BUILD_TYPE=Debug")
  fi

  rm -rf "${srcdir}/build-${MINGW_CHOST}"
  mkdir "${srcdir}/build-${MINGW_CHOST}"
  cd "${srcdir}/build-${MINGW_CHOST}"

  MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
  ${MINGW_PREFIX}/bin/cmake.exe \
    -G"MSYS Makefiles" \
    -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
    ${extra_config} \
    "../${_realname}-${pkgver}"

  make
}

check() {
  cd "${srcdir}/build-${MINGW_CHOST}"
}

package() {
  cd "${srcdir}/build-${MINGW_CHOST}"
  install -Dm644 liberime-core.dll ${pkgdir}${MINGW_PREFIX}/bin/liberime-core.dll
  install -Dm644 ${srcdir}/${_realname}-${pkgver}/README.org ${pkgdir}${MINGW_PREFIX}/share/liberime/README.org
  install -Dm644 ${srcdir}/${_realname}-${pkgver}/liberime.el ${pkgdir}${MINGW_PREFIX}/share/emacs/site-lisp/liberime.el
}

```

**Comment by DogLooksGood** [comment]
librime的msys包，含有librime里面的.h文件吗

**Comment by tumashu** [comment]
包含

**Comment by tumashu** [comment]
```
完全可以用上面的这个脚本：
https://github.com/merrickluo/liberime/blob/master/msys2-build.sh
略作修改，去掉构建 liberime 包、zip 的时候重新组织一下路径和文件，做成像 librime-osx 那种结构就可以了。甚至不用修改，从生成的 zip 里（ https://github.com/merrickluo/liberime/releases/download/v0.0.3/liberime-v0.0.3-windows-x86_64.zip ）抽出需要的那几个文件就好了。
我个人更建议直接给构建好了的windows包，把 librime.dll 甚至 librime-emacs.dll 直接给用户，不用再编译了。可以分 win32 （这个 librime 官方有）、win64 两个 release。这对不想折腾，开箱即用的人来说非常方便。
对于想自己编译的用户，整理上文，形成文档，自行折腾，乐在其中。
```
我发布了 liberime v0.0.6， 在二进制包里面添加了 .a .h 和 cmake 配置文件， 方便你们折腾，msys2-build.sh 放到 tools 目录了，也做了极大的简化，用到 emacs-rime 也就改几行代码

**Comment by tumashu** [comment]
https://github.com/merrickluo/liberime/blob/master/tools/liberime-msys2-build.sh

**Comment by DogLooksGood** [comment]
我面临的问题主要是我没有 Windows 的系统，所以还没有测试的办法。

**Comment by tumashu** [comment]
你当时基于什么原因考虑，fork出 lib.c的，fork c代码比elisp后期维护工作量大多了

**Comment by DogLooksGood** [comment]
实际上 fork lib.c 出来后只需参考各 rime 的前端实现来调整，比如 ibus-rime, fcitx-rime 等。而不需要考虑修改 C 代码的 break changes 对其它项目的影响。

对于 librime 来讲，他提供给前端的 api 本身就是一比一的，不需要调整，所以 librime.el 对 emacs-rime 来讲其中很多部分是多余和不准确的。

另外 liberime 需要 cmake，我不希望有这个依赖。在 archlinux 上零配置能自动搞定所有问题是第一目标。

Windows 的构建问题在于我本人没有 Windows 所以无论方案是什么我都没有办法验证。所以只能等待某个人提供出完整的方案。

**Comment by tumashu** [comment]
cmake的引入，我感觉是最开始借鉴 libegit2的时候，顺手捎带过来的，我在折腾 liberime window的时候，也感觉到它有点杀鸡牛刀了，我准备把 liberime也换成简单的 makefile

**Comment by DogLooksGood** [comment]
现在这个问题并不是 emacs-rime 的动态库构建的难点，实际上 emacs-rime 的构建已经是最简单的情况了。难点是 Windows 上面怎么构建 librime 的问题，并不在这个项目的范围之内。

**Comment by chuxubank** [comment]
现在在 Windows 上 使用 `librime` 简单了许多，多谢 @tumashu !
大致说下目前在 `doom-emacs` 下使用 `emacs-rime` 的步骤，如有错误请指正。
1. 安装 msys2, `pacman -Syu`
2. 安装 mingw-w64 版本的 `emacs` , `librime`, `gcc`
    - 需要将 `C:\msys64\mingw64\bin` 添加到系统 `Path` 环境变量中
    - 这个版本的 Emacs 有动态模块的支持
3. 使用 mingw64 的终端 cd 到 如下目录 `~/.emacs.d/.local/straight/build/rime`
4. `gcc lib.c -o librime-emacs.dll -fpic -O2 -Wall -shared -lrime`
5. 安装 小狼毫 0.14.3
6. doom 里的配置可以参考[我的 doom 配置](https://github.com/chuxubank/.doom.d/tree/master/modules/input/chinese%2B)
---
目前的问题
- 选中 明月拼音·简化字 后依然为繁体，可能是 https://github.com/DogLooksGood/emacs-rime/issues/64#issuecomment-605466655 所说的opencc原因。

**Comment by chuxubank** [comment]
今天又折腾了一下，在不改变 `rime.el` 和 `Makefile` 的情况下也能使用 `rime-compile-module` 完成 `librime-emacs.dll` 的编译。
1. 安装 msys2 以及 mingw-w64 版本的 `emacs` , `librime`, `gcc`
2. 设置 `SHELL` 环境变量为 `C:\msys64\usr\bin\bash.exe` 即可, 参考 [Single Shell Commands](https://www.gnu.org/software/emacs/manual/html_node/emacs/Single-Shell.html)

**Comment by DogLooksGood** [comment]
可否提个windows的安装说明的PR?
