### ISSUE TITLE
*scratch* buffer里posframe位置异常

### ISSUE THREAD

**Issue by XiaoGeMa** [DogLooksGood/emacs-rime#68]
posframe候选框出现在最下方而不是跟随方式。

**Comment by DogLooksGood** [comment]
需测试下在 emacs -Q 下是否问题存在。如果用 package, 那么本项目 clone 下来之后，make test即可。如果使用 straight 则需自行准备脚本。

还需要emacs版本和系统信息。

**Comment by DogLooksGood** [comment]
Close due to no more information.
