### ISSUE TITLE
状态栏乱码

### ISSUE THREAD

**Issue by keke-cute** [DogLooksGood/emacs-rime#69]
[![GVsYE6.png](https://s1.ax1x.com/2020/03/29/GVsYE6.png)](https://imgchr.com/i/GVsYE6)
和pyim一个问题 https://github.com/tumashu/pyim/issues/341
但是pyim可以用(setq pyim-title "xxx")解决乱码，请问emacs-rime有没有这种

**Comment by Z572** [comment]
` (setq rime-title "xxx") `

**Comment by cnsunyour** [comment]
貌似是 straight 在生成 autoload 文件时会把中文转码，把 rime-title 改成英文字符就好了。

**Comment by Z572** [comment]
直接在 `use-package` 的 `:custom` 里加 `(rime-title "ㄓ")` 就可以了

**Comment by DogLooksGood** [comment]
如果 defvar 那行改成 
```
(defvar rime-title (char-to-string 12563))
```
是否可以解决在 straight 上的问题？

**Comment by keke-cute** [comment]
> @cnsunyour 求测试
> 
> 如果 defvar 那行改成
> 
> ```
> (defvar rime-title (char-to-string 12563))
> ```
> 
> 是否可以解决在 straight 上的问题？

会！解决了，谢谢，请改一下这行吧

**Comment by cnsunyour** [comment]
> @cnsunyour 求测试
> 
> 如果 defvar 那行改成
> 
> ```
> (defvar rime-title (char-to-string 12563))
> ```
> 
> 是否可以解决在 straight 上的问题？

我这里无法复现，很早我给 doom 反馈过这个问题，它里面已经修复了，就是在生成 autoload 文件时不会对中文进行转码了。

**Comment by DogLooksGood** [comment]
那我们先应用这个修改来避免类似的问题吧。
