### ISSUE TITLE
Symbol’s function definition is void: liberime-string-length

### ISSUE THREAD

**Issue by lyserenity** [DogLooksGood/emacs-rime#7]
message 显示 `rime--show-candidate: Symbol’s function definition is void: liberime-string-length`。
因为我用的是 `merrickluo/liberime` 的 repo，跟这个有关吗？还是可能是哪里有问题？（除了没候选之外，打字没有问题）

**Comment by DogLooksGood** [comment]
有关的，`liberime-string-length` 还没有发 PR 合并过去。

**Comment by lyserenity** [comment]
`error in process sentinel: liberime: building failed with exit code 2`，不知道为什么在 emacs 里一直编译不过。
抱歉，因为对这些不熟，请问这步是要成功编译出 liberime.so 吗？如果已经在外部编译完了，要怎么设定让它认出文件放在哪？谢谢

**Comment by DogLooksGood** [comment]
是的，是要编译出liberime.so。如果你已经编译好了，你需要知道插件按装的位置。

你那里有 ~/.emacs.d/elpa 这个目录么？如果有的话，里面就会有类似 `liberime-config-20200310.331` 这样的目录。

那么最后 liberime.so要放的位置就是 `~/.emacs.d/elpa/liberime-config-20200310.331/build/liberime.so`

**Comment by DogLooksGood** [comment]
另外，如果编译不过的话，可以看下能否找到编译错误的信息。如果你单独编译liberime，用的指令应该是在liberime的项目目录下`make liberime`.

**Comment by lyserenity** [comment]
我把编译好的文件放到目录（~/.emacs.d/elpa/...）下之后就成功了，感谢！很好用！
