### ISSUE TITLE
[macOS] emacs-mac 的 cask 版本无法使用 librime-emacs.so

### ISSUE THREAD

**Issue by chuxubank** [DogLooksGood/emacs-rime#71]
- macOS 10.15.4
- emacs-mac: emacs-26.3-z-mac-7.9 (cask)

无论是使用
```bash
ln -s /Applications/Emacs.app/Contents/Resources/include/emacs-module.h /usr/local/include
```
还是使用
```lisp
(setq rime-emacs-module-header-root "/Applications/Emacs.app/Contents/Resources/include")
```
build 出来的 `librime-emacs.so` 文件都无法直接加载

**错误信息**
```
load-file: Module could not be opened: "/Users/misaka/.doom/.local/straight/build/rime/librime-emacs.so", "dlopen(/Users/misaka/.doom/.local/straight/build/rime/librime-emacs.so, 1): no suitable image found.  Did find:
	/Users/misaka/.doom/.local/straight/build/rime/librime-emacs.so: code signature in (/Users/misaka/.doom/.local/straight/build/rime/librime-emacs.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/Users/misaka/.doom/.local/straight/build/rime/librime-emacs.so: stat() failed with errno=4"
```

```bash
➜  rime git:(develop) codesign --display --verbose librime-emacs.so
librime-emacs.so: code object is not signed at all
```

使用非 cask 版本, 则正常...
考虑到可能有一部分人可能使用的是 cask 版本, 如果能解决这个问题应该会方便很多.

**Comment by DogLooksGood** [comment]
猜测有没有可能是 Cask 和 dylib 不是在同一个机器编译导致的？

**Comment by chuxubank** [comment]
应该不是主要原因？
因为原先在 cask 版本上使用 liberime 没有问题
另外我 build 出来 是`.so` 文件，这个有关系吗？

**Comment by DogLooksGood** [comment]
build 出来是 .so 的似乎是 mac emacs 26 的 `module-file-suffix` 是 `.so`，27 里面修正了这个问题。

可能需要比对一下 liberime 最后构建的命令和 emacs-rime 在 mac 上面的区别。目前没有什么头绪。

**Comment by chuxubank** [comment]
好的，不着急，开 issue 主要是想记录一下，我有时间的话自己研究研究

**Comment by wsw0108** [comment]
https://stackoverflow.com/questions/13695466/mac-os-x-code-signing-and-executable-validation

可能liberime用的cmake处理了这个code signature

**Comment by cnsunyour** [comment]
这可能不是个案问题，我注意到 libvterm 在 brew cask 安装的 emacs-mac 里也是不能正常编译的。

**Comment by chuxubank** [comment]
> 可能liberime用的cmake处理了这个code signature

有可能, 今天大致看了一下 liberime 的 [CMakeLists.txt](https://github.com/merrickluo/liberime/blob/master/CMakeLists.txt), 感觉可能是
```cmake
add_library(erime-core SHARED "")
```
这个设置会产生影响 (全凭猜测, 没咋用过 make 和 cmake).
以及参考 @cnsunyour 所说 libvterm 也不能加载的问题, 对比 [libvterm](https://github.com/akermu/emacs-libvterm/blob/master/CMakeLists.txt) 用的是
```cmake
add_library(vterm-module MODULE vterm-module.c utf8.c elisp.c)
```
最后贴一下 CMake 的文档 [add_library](https://cmake.org/cmake/help/latest/command/add_library.html?highlight=add_library#normal-libraries).
但是依然不知道和 macOS 的签名有什么联系...

**Comment by wsw0108** [comment]
其他地方有个类似的问题，https://github.com/Shougo/vimproc.vim/issues/284#issuecomment-552091559

要是能让cask把Emacs安装到其他路径，可能就可以了。
没有mac环境，仅作参考。

**Comment by chuxubank** [comment]
但 cask 其实就是装了个 `Emacs.app` 到 `/Applications` 目录下, 然后软链接 `/usr/local/bin/emacs`
```
==> Artifacts
Emacs.app (App)
/Applications/Emacs.app/Contents/MacOS/Emacs.sh -> emacs (Binary)
/Applications/Emacs.app/Contents/MacOS/bin/ebrowse (Binary)
/Applications/Emacs.app/Contents/MacOS/bin/emacsclient (Binary)
/Applications/Emacs.app/Contents/MacOS/bin/etags (Binary)
```
这些应该都不是受 SIP 保护的目录...

**Comment by chuxubank** [comment]
今天再次确认了一下, liberime 在 emacs-mac 的 cask 版本中也无法使用, 而在 formular 版中则可以使用, 基本确定是新 cask 的锅.

**Comment by DogLooksGood** [comment]
随着 dynamic module 的使用变多，我觉得这个问题应该会很快得到修复。

**Comment by railwaycat** [comment]
vterm 也有同样的问题，但找不到好的办法…感觉目前可行的只有不给 cask 做签名了

https://github.com/railwaycat/homebrew-emacsmacport/issues/192

**Comment by chuxubank** [comment]
> vterm 也有同样的问题，但找不到好的办法…感觉目前可行的只有不给 cask 做签名了
> 
> [railwaycat/homebrew-emacsmacport#192](https://github.com/railwaycat/homebrew-emacsmacport/issues/192)

https://github.com/eraserhd/parinfer-rust/blob/master/extra-docs/MacOS-Code-Signing.adoc

之前看到这篇文章说可能是 Entitlements 的问题？

`com.apple.security.cs.disable-library-validation` entitlement

**Comment by railwaycat** [comment]
@chuxubank 感谢思路，我用这个 entitlement 搞定了！

emacs-mac 新的 cask release 已经可以使用 dynamic module 了。
