### ISSUE TITLE
在使用scala-mode时，rime可时，输入中文后按空格后，posframe提示未自动消失

### ISSUE THREAD

**Issue by cxb811201** [DogLooksGood/emacs-rime#72]
在使用`scala-mode`时，`rime`可时，输入中文后按空格后，`posframe`提示未自动消失
在其他`mode`(如：`text-mode`、`sql-mode`)里输入中文后按空格后，`posframe`提示会自动消息

**Comment by DogLooksGood** [comment]
Hi, 可以重现问题。

初步判断似乎 scala-mode 会在使用中不断重置 post-self-insert-hook. 
但这个 hook 对于 emacs-rime 来说是必要的。

一个简单的 hack 方式是在 scala-mode 中换用 post-command-hook
```
(add-hook 'scala-mode-hook
  (lambda () 
    (add-hook 'post-command-hook 'rime--redisplay nil t)))
```

**Comment by Z572** [comment]
或许可以用 add-variable-watcher 来刷新? 就可以不要用 post-self-insert-hook

https://www.gnu.org/software/emacs/manual/html_node/elisp/Watching-Variables.html#Watching-Variables

**Comment by DogLooksGood** [comment]
@Z572 这里用 post-self-insert-hook 应该是最合理的做法。
