### ISSUE TITLE
请问，是要怎么激活，rime的效果还是和没有安然emacs-rime前一致

### ISSUE THREAD

**Issue by yxsongbo** [DogLooksGood/emacs-rime#74]
我的librime安装方式是 apt install librime-dev，版本是1.4.0
按C-\ 提示variable 'module-file-suffix' is null

**Comment by DogLooksGood** [comment]
需要 emacs 的动态模块功能支持。

**Comment by yxsongbo** [comment]
emacs的动态模块功能要怎么打开呢

**Comment by Z572** [comment]
需要下载具有动态模块的版本，或者从源代码编译

**Comment by yxsongbo** [comment]
從源碼編譯的是librime嗎，我已經下載了最新的1.5.3編譯了，動態模塊是指？

**Comment by yxsongbo** [comment]
還有我的系統fcitx-rime無法切換爲簡體字了，要怎麼解決？

**Comment by Z572** [comment]
指的是 emacs, 在编译的时候开启动态模块的支持

**Comment by yxsongbo** [comment]
我的系統是ubuntu 19.10，通過命令apt install emacs安裝的，現在應該怎麼開啓動態模塊支持？

**Comment by Z572** [comment]
按 <kbd> f4 </kbd> 打开方案选单 选择简体字
或者
打开 useer.yaml 把simplification 选项改为 true 再重新打开 fcitx

**Comment by yxsongbo** [comment]
也不行，會不會是我安裝過openCC造成的

**Comment by Z572** [comment]
> sudo add-apt-repository ppa:kelleyk/emacs -y
sudo apt-get update
sudo apt install emacs27

试试, 我不用 ubuntu 不确定可不可以

**Comment by Z572** [comment]
> 也不行

是怎样不行? 建议录个 gif 看看

**Comment by DogLooksGood** [comment]
简单的方式就是装 emacs27。有默认打开的动态模块支持。

**Comment by yxsongbo** [comment]
![Peek 2020-04-01 16-30](https://user-images.githubusercontent.com/135945/78116096-6339a680-7436-11ea-901a-891f37849be6.gif)

**Comment by yxsongbo** [comment]
费了半天功夫，装起来的竟然是emacs 28.0，我还连27都没见过呢，前边的朋友提供的方法最高只能装到26.3

**Comment by yxsongbo** [comment]
![rime](https://user-images.githubusercontent.com/135945/78117360-25d61880-7438-11ea-8dbf-1551ac5dbbb1.gif)

**Comment by yxsongbo** [comment]
我按C-\ 就提示compile rime dynamic error

**Comment by Z572** [comment]
``` elisp
(format "cd %s; env %s make lib" rime--root (rime--build-compile-env))
```
执行一下

**Comment by yxsongbo** [comment]
![Screenshot from 2020-04-01 17-13-25](https://user-images.githubusercontent.com/135945/78120231-27094480-743c-11ea-8aca-cedd8b0efd41.png)

**Comment by yxsongbo** [comment]
我的执行方式有问题吗，我在配置文件中添加了 (LIBRIME_ROOT=~/.emacs.d/librime/dist/ make lib)
之后，没有提示错误，但提示我current input method rfc1347

**Comment by Z572** [comment]
先 ` (require 'rime) ` 啊

**Comment by yxsongbo** [comment]
(require 'evil)
(evil-mode 1)


(require 'rime)

(use-package rime
  :custom
  ;;; (rime-librime-root "~/.emacs.d/librime/dist")
  ;;; (LIBRIME_ROOT=~/.emacs.d/librime/dist/ make lib)
  (default-input-method "rime"))

(format "cd %s; env %s make lib" rime--root (rime--build-compile-env))

**Comment by yxsongbo** [comment]
又出现compile rime danamic error 了

**Comment by Z572** [comment]
在 package 目录里面 `make lib` 试一下。

**Comment by DogLooksGood** [comment]
编译失败的情况下，在 *Shell command* 那个buffer 中会有错误。

**Comment by yxsongbo** [comment]
For information about GNU Emacs and the GNU system, type C-h C-a.
Package cl is deprecated
gcc lib.c -o librime-emacs.so -fPIC -O2 -Wall -shared -lrime
lib.c:24:10: fatal error: rime_api.h: No such file or directory
   24 | #include <rime_api.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:40: lib] Error 1
rime-compile-module: Compile Rime dynamic module failed
Updating buffer list...
Formats have changed, recompiling...done
Updating buffer list...done
ibuffer-projectile: groups set

**Comment by Z572** [comment]
先执行 `dpkg -L librime-dev` 找到 rime_api.h 的路径, 
再设置环境变量 `C_INCLUDE_PATH` 到它的目录

**Comment by DogLooksGood** [comment]
也许是时候装个 ubuntu 研究下在上面的构建流程了。这个 librime-dev 每个人安装出来的版本都不一样。而且往往装完 .h 也不会在系统的路径中，感觉好奇怪。

**Comment by yxsongbo** [comment]
我现在的解决办法是下载了mac版的librime，虽然我用的是Ubuntu 19.10，
wget https://github.com/rime/librime/releases/download/1.5.3/rime-1.5.3-osx.zip
unzip rime-1.5.3-osx.zip -d ~/.emacs.d/librime
rm -rf rime-1.5.3-osx.zip

**Comment by yxsongbo** [comment]
现在正在攻克同步词库

**Comment by yxsongbo** [comment]
执行 M-x rime-sync 的时候提示 you should enable rime before deploy

**Comment by DogLooksGood** [comment]
这。。。Mac 版的 librime 在 ubuntu 上面是可用的吗？
#42 #43 有两个 issue 和这个 ubuntu 上的使用都有关。

rime-sync需要先激活输入法。

**Comment by yxsongbo** [comment]
是的，我的操作系统是ubuntu 19.10，下载了https://github.com/rime/librime/releases/download/1.5.3/rime-1.5.3-osx.zip，文件名中有osx，应该是mac版的预编译吧

同步成功实现，所谓的emable rime并不是说可以用emacs-rime输入就激活了，要M-x rime-mode之后才算enable rime

**Comment by yxsongbo** [comment]
你的字体大小配置文件可以给我参考下吗？

**Comment by yxsongbo** [comment]
小鹤双拼方案可以怎么添加？

**Comment by DogLooksGood** [comment]
> 同步成功实现，所谓的emable rime并不是说可以用emacs-rime输入就激活了，要M-x rime-mode之后才算enable rime

不应该是这样的，`rime-mode` 不是用来手工激活的。应该只是使用（默认）<kbd>C-\\</kbd>激活 emacs-rime，就可以正常使用。

> 你的字体大小配置文件可以给我参考下吗？

我没有什么特别的字体大小的配置。

> 小鹤双拼方案可以怎么添加？

Rime 的布署一般来说是从安装 rime 产生的 rime-share-data-dir 默认在 /usr/share/rime-data 应该，布署到 特定目录，这里是 ~/.emacs.d/rime 。这样每次不管布署到哪里，都可以有相同的配置。

如果你的配置是直接放在 .config/fcitx/rime 里面，那么你需要在 ~/.emacs.d/rime 生成后，复制一份过去。对于 Rime 来说，每一个 Rime 前端都有一个配置，他们之间可以同步。

**Comment by yxsongbo** [comment]
好像切换不同的输入方案Ctrl+grave（·）和emacs中的其他键冲突了，怎么设置？

**Comment by DogLooksGood** [comment]
通过把这个组合键送给 Rime 

https://github.com/DogLooksGood/emacs-rime#open-rime-menu

**Comment by yxsongbo** [comment]
字号大小怎么调？

**Comment by yxsongbo** [comment]
(use-package rime
  :bind
  (:map rime-mode-map
   ("C-`" . 'rime-send-keybinding))

  :custom
  (
   (default-input-method "rime")
   (rime-librime-root "~/.emacs.d/librime/dist")
   (rime-show-candidate 'posframe)))

能帮我看下这个配置错在什么地方吗？

**Comment by DogLooksGood** [comment]
> 字号大小怎么调？

你是指候选框的字体大小吗？如果你使用的 posframe 展示候选的话。

rime-posframe-properties 里面可以指定 `:font` 

可以设置值例如 `"Sarasa UI SC-10"`

**Comment by Z572** [comment]
` 'rime-send-keybinding ` 不要单引号

**Comment by DogLooksGood** [comment]
> `'rime-send-keybinding` 不要单引号

这个单引号有也没有关系

@yxsongbo 你这个配置遇到什么问题了吗？

**Comment by DogLooksGood** [comment]
Continue in #75

**Comment by yxsongbo** [comment]
切换输入方案的快捷键对了
