### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by davidmlw** [DogLooksGood/emacs-rime#79]
**问题描述**

debian, emacs/26.3 安装好librime 1.5.3。
C-\ 显示：“rime--build-compile-env: Variable ‘module-file-suffix’ is nil”

简明的问题描述

**Emacs中的配置**

```
(use-package rime
  :custom
  (default-input-method "rime"))
```

**复现方式**（安装遇到问题时省略）

复现问题所需的操作

**是否可在 emacs -Q 中复现**

是/否

**截图**

展示错误的截图或动图

**环境信息**

- 操作系统：如 ArchLinux
- Emacs版本：如 27.0.90
- Librime版本：如 1.5.3
- Librime安装方式：包管理器/手工编译
- 安装方式：Git/Melpa/Straight/Quelpa

**Comment by Z572** [comment]
应该是你的 emacs 不支持动态模块, 换个支持的就好了.

**Comment by DogLooksGood** [comment]
需要所用 emacs 支持动态模块特性。

**Comment by davidmlw** [comment]
重新编译了一个带emacs-module的26.3，现在能正常编译librime-emacs.so，但是在回答y之后出现了一个错误。

gcc lib.c -o librime-emacs.so -fPIC -O2 -Wall -I /home/david/Downloads/emacs-26.3/src/ -shared -lrime
Compile succeed!
Rime will use /home/david/.emacs.d/rime/ as the user data directory,
first time deploy could take some time. Continue? (y or n) y
rime--load-dynamic-module: Wrong type argument: stringp, nil

**Comment by DogLooksGood** [comment]
打开 toggle-debug-on-error
重现问题的话会打印一个异常栈，可以贴出来看下。

另外需要一些额外的信息，比如安装 rime 的方式。

**Comment by davidmlw** [comment]
rime 采用 make install， 1.5.3

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  rime--load-dynamic-module()
  rime-activate("rime")
  apply(rime-activate "rime" nil)
  activate-input-method("rime")
  toggle-input-method(nil 1)
  funcall-interactively(toggle-input-method nil 1)
  call-interactively(toggle-input-method nil nil)
  command-execute(toggle-input-method)

**Comment by DogLooksGood** [comment]
检查一下 `rime-share-data-dir` 和 `rime-user-data-dir` 的指。
前者是 rime-data 的目录，一般在类似 `/usr/share/rime-data`， 后者是布署 rime 配置的目录，一般在 `~/.emacs.d/rime`.

猜测大概率需要指定 `rime-share-data-dir` ，应该是在类似 `/usr/share/rime-data`。这个值通常会自动设定，如果没有的话则需要手动。

**Comment by davidmlw** [comment]
rime-share-data-dir is nil. 但是 /usr/share/rime-data 也不存在。

**Comment by davidmlw** [comment]
librime-1.5.3 是download https://github.com/rime/librime/archive/1.5.3.tar.gz
make 
sudo make install

**Comment by davidmlw** [comment]
虽然 /usr/share/rime-data 不存在，但是 (setq rime-share-data-dir "/usr/share/rime-data") 之后
emacs-rime is activated
但是输入法没有起作用
是否系统还需要安装 rime相关的输入法？

**Comment by Z572** [comment]
要把 rime-share-data-dir 设置成 make install 的具体位置, 是一个有很多 yaml 文件的文件夹.

**Comment by davidmlw** [comment]
我感觉这个标准包的安装没有包括你说的yaml文件目录。

-- Install configuration: "Release"
-- Installing: /usr/lib/pkgconfig/rime.pc
-- Installing: /usr/share/cmake/rime/RimeConfig.cmake
-- Installing: /usr/include/rime_api.h
-- Installing: /usr/include/rime_levers_api.h
-- Installing: /usr/lib/librime.so.1.5.3
-- Installing: /usr/lib/librime.so.1
-- Set runtime path of "/usr/lib/librime.so.1.5.3" to ""                                                        
-- Installing: /usr/lib/librime.so
-- Installing: /usr/bin/rime_dict_manager
-- Set runtime path of "/usr/bin/rime_dict_manager" to ""                                                       
-- Installing: /usr/bin/rime_deployer
-- Set runtime path of "/usr/bin/rime_deployer" to ""
make[1]: Leaving directory '/home/david/Downloads/librime-1.5.3/build'

**Comment by Z572** [comment]
我搞错了, 在 arch 上是 librime-data, 在 debian 里不知道叫什么,或者你可以下载
https://github.com/rime/rime-prelude 放 /use/share/rime-data/ 里, 应该是可以用的

**Comment by davidmlw** [comment]
还需要装ibus-rime

**Comment by Tinker-S** [comment]
安装报错
`rime--load-dynamic-module: wrong type argument: stringp, nil`
开启 toggle-debug-on-error 看了一下， 是 rime-shared-data-dir 为nil导致的，按照楼上所述，安装 ibus-rime 后问题解决。
rime-shared-data-dir自动设置为 /usr/share/rime-data
