### ISSUE TITLE
shift 无法切换中英文

### ISSUE THREAD

**Issue by aur3l14no** [DogLooksGood/emacs-rime#8]
能否添加相关支持？

**Comment by DogLooksGood** [comment]
Emacs 无法捕获到单独的 Shift 按键。有些人使用一些其它软件，将单独按 Shift 模拟成其它按键，个人觉得成本很高，可靠性也不好保证。

在 emacs-rime 可以获得 Emacs 状态的情况下，我更倾向于：
1. 跟据场景自动切换的方式
2. 可以不用记忆当前状态的方式

**Comment by aur3l14no** [comment]
可惜了，主要是 org 文档混合写的时候规律性弱，不好制定规则。

**Comment by DogLooksGood** [comment]
代码英文，文西中文，两个~之间英文，英文之后英文。

目前我能想到的大概是这样。

如是中文中的英文就是 Hello 这样，或~hello~这样。

**Comment by aur3l14no** [comment]
嗯嗯，另外希望 <Return> 上屏英文的时候，最好能去掉字母中间的空格... 不知道这个应该怎么设置...

**Comment by aur3l14no** [comment]
总之谢谢了，不过我本人是用 emacs org mode 多过写代码，所以感觉还是更方便进行 **无规律** 的中英文切换的外置输入法比较适合我 :)

**Comment by yxsongbo** [comment]
在输入中文的情况下，如何快速的输入英文标点？

**Comment by DogLooksGood** [comment]
@yxsongbo 
你指一段时期默认到英文标点，还是输入单一英文标点？

**Comment by yxsongbo** [comment]
单一英文标点

**Comment by DogLooksGood** [comment]
三种思路
1. 有断言能进入临时英文。
2. 手动切输入法两次。
3. Rime 中让标点不要直接上屏，比如 ~ 可以有 ~ 和 ～ 两个候选，就可以用回车直接上屏输入的编码。
