### ISSUE TITLE
如何不让 Helm 中继承输入法的状态

### ISSUE THREAD

**Issue by davidmlw** [DogLooksGood/emacs-rime#80]
**问题描述**

M-x C-* 如何自动关闭输入法？

**Comment by Z572** [comment]
什么配置? C-* 是什么命令?

**Comment by davidmlw** [comment]
M-x, 和 Ctrl-开头的各种快捷键和命令。
一旦离开正在编辑的buffer，进入emacs控制的状态，比如输入文件名，helm搜索，最好能够自动关闭输入法。

**Comment by Z572** [comment]
可以用 `(add-hook 'clone-buffer-hook 'deactivate-input-method)` 试试

**Comment by DogLooksGood** [comment]
emacs 当中输入法状态是 buffer 相关的，如果离开了正在编辑的 buffer 理应是关闭的状态。

**Comment by davidmlw** [comment]
这应该是emacs-rime最吸引人的地方。因为其他的输入法不可能做到这一点。

**Comment by cnsunyour** [comment]
那么这个 issue 的问题到底是？

**Comment by davidmlw** [comment]
不是一个bug，是一个featrure requirement。但是我不熟练把它标记成bug了。

**Comment by cnsunyour** [comment]
我还是没懂，这不已经是本身就有的功能吗？怎么还是 feature requirement 呢？

**Comment by DogLooksGood** [comment]
我觉得可以说一下现在的行为和你期望的行为的差别。

**Comment by davidmlw** [comment]
我的emacs 26.3 好像不是这样工作的，M-x 的minibuffer的输入法状态是跟随当前buffer的。

**Comment by DogLooksGood** [comment]
能在 emacs -Q 中重现问题吗。

**Comment by cnsunyour** [comment]
奇怪，我在 26.3 和 27 里都是正常的。可能还是和你的配置环境有关系。

**Comment by davidmlw** [comment]
嗯，我用emacs -Q，然后仅仅启动 emacs-rime，行为和预期是一样的。看了是我装载的其他什么包的问题。有时间逐个加载试一下

**Comment by davidmlw** [comment]
可以确认是装载helm之后，行为就变了。但是我不知道如何修正。

**Comment by DogLooksGood** [comment]
那可以在 rime-disable-predicates 加一个判断当前的 mode 是不是 helm 相关 mode 的。

**Comment by cnsunyour** [comment]
试试 
```
(add-hook ‘helm-mode-hook #'deactivate-input-method)
```
 可以不

**Comment by davidmlw** [comment]
没管用。
我觉得是当前的buffer里有个什么属性，被helm继承了。

**Comment by davidmlw** [comment]
当执行helm-M-x的时候，它还特地说 “Rime activate.”

**Comment by cnsunyour** [comment]
感觉你要检查 helm 的配置了，这是主动触发激活输入法了。

**Comment by davidmlw** [comment]
与helm的配置没有关系。
不价值helm的配置，只是M-x然后调用helm-M-x，就会打开输入法。
M-x的时候还是正常的。

**Comment by davidmlw** [comment]
我感觉是 current-input-method 被继承了。

**Comment by davidmlw** [comment]
你们的helm都是按预期工作的吗？

**Comment by Z572** [comment]
我不用 helm

**Comment by DogLooksGood** [comment]
输入法是有可能有继承的情况，isearch里面就有类似的机制。但是没有关系，因为你可以通过设置 rime-disable-predicates 让输入法在 helm 中处于英文状态，这样就没有影响。

**Comment by DogLooksGood** [comment]
```
(setq rime-disable-predicates
      '(helm--alive-p))
```
尝试下这个配置。

**Comment by davidmlw** [comment]
Helm有专门的customization

Helm-Inherit-Input-Method
