### ISSUE TITLE
更新文档，doom-mode-line不再需要hack

### ISSUE THREAD

**Issue by DogLooksGood** [DogLooksGood/emacs-rime#81]

**Comment by cnsunyour** [comment]
doom-mode-line 哪里更新了？麻烦告诉我下，我没找到呢

**Comment by DogLooksGood** [comment]
https://github.com/seagle0128/doom-modeline/blob/bead0d0cec9cc10ed94fb9052b7737b00016fd75/doom-modeline-segments.el#L196

看起来已经可以自动的显示提示符了。

**Comment by cnsunyour** [comment]
唔~看到了。 doom-emacs 里的 modeline 应该是还在固定到之前的版本，所以没更新。

**Comment by cnsunyour** [comment]
建议文档再保留一阵子，以免有些人的 doom-modeline 还没有更新，可以加个注释，说明一下从哪个 commit 开始不再需要 hack 了。

**Comment by cnsunyour** [comment]
我这里更新后测试的结果并没有实现动态变化图标的功能，但是看代码又没看出什么问题。

**Comment by cnsunyour** [comment]
报告，今天重新下载又测了一下，没问题了。

**Comment by DogLooksGood** [comment]
去掉了 Faq 中的相关内容。

**Comment by yuanl** [comment]
我现在 Doom-Emacs 换成`(modelight +light)`就不会显示提示符。现在要怎么做呢？

**Comment by DogLooksGood** [comment]
@yuanl 可能应该在 doom-mode-line 开个 issue

**Comment by cnsunyour** [comment]
> 我现在 Doom-Emacs 换成`(modelight +light)`就不会显示提示符。现在要怎么做呢？

我记得 (modelight +light) 就不是用 doom-modeline package了
