### ISSUE TITLE
posframe 的更新可能解决了偶尔吃字的问题

### ISSUE THREAD

**Issue by cnsunyour** [DogLooksGood/emacs-rime#82]
@tumashu 回复说 https://github.com/tumashu/posframe/commit/b71b530ff73b56f956097d844db2cd66dc0e632b 可能解决了 https://github.com/tumashu/posframe/issues/59 偶尔“吃”字的问题。
正在测试，但现在不好确定是否已修复，还需要段时间。如证实确已修复，就可将文档中的相关说明去除了。

**Comment by DogLooksGood** [comment]
地球拼音里面输入个 h 然后一直翻页，就能遇到这个情况。

**Comment by cnsunyour** [comment]
那就是说还是没修复这个情况？

**Comment by cnsunyour** [comment]
果然用地球拼音复现了，已向 posframe 反馈。
