### ISSUE TITLE
小建议：把必须为英文模式的断言固定至默认规则下

### ISSUE THREAD

**Issue by cnsunyour** [DogLooksGood/emacs-rime#85]
具体说，即把一些必须要切换到英文模式的断言固定到类似 `rime-disable-predicates` 的规则中，而无需配置，用户的配置是在此规则上自行搭配断言函数。这样可以减少用户配置的复杂度，降低入门用户的配置门槛。
个人推荐以下断言适合固定：

> rime-predicate-evil-mode-p
> rime-predictte-ace-window-p
> rime-predicate-hydra-p
> (button-at (point))

不知意下如何？

**Comment by DogLooksGood** [comment]
像之前所说的提供一个函数进行自动配置，而不是把这个变量的值写死？

我觉得写死不好，因为不是每个人都用这些插件，如果所有常用的插件都列进去，默认会相当多。

在一个函数中进行逐个判断创建一个默认值才更合理。不过还不知道合适的调用时机。

**Comment by cnsunyour** [comment]
确实写死的话就会使得默认断言比较多，只是考虑到很多人开始不能理解断言的作用，配置起来有好多奇奇怪怪的问题，即使给了他们默认配置，也会被后来的自定义配置破坏掉。
我也不知道有什么更好的方法来帮助入门用户，所以不想了这么一个暴力方法。

**Comment by cnsunyour** [comment]
先关了，突然有了这么一个想法，现在来看还没有十分的必要性。
