### ISSUE TITLE
请问要怎么配置才能自动中英文切换呢，比如我在输入emacs.d的时候，其中的“."能根据我输入的是ascii字符而自动把”。“切换为"."

### ISSUE THREAD

**Issue by yxsongbo** [DogLooksGood/emacs-rime#87]

**Comment by cnsunyour** [comment]
在 `rime-disable-predicates` 或 `rime-inline-predicates` 中按你的需要设置对应的断言函数组合就可以了。readme 中有断言函数列表，也可以看 `rime-predicates.el` 文件中的断言定义。

**Comment by yxsongbo** [comment]
左shift键无法切换中英文输入：

rime的 default.custom.yaml 配置如下：
patch:
  schema_list:
    - schema: luna_pinyin_simp
    - schema: double_pinyin_flypy
  menu/page_size: 7

  "ascii_composer/switch_key":
      Caps_Lock: commit_code
      Control_L: inline_ascii
      Control_R: noop
      # 左右Shift上屏编码并切换为英文状态，
      # inline_ascii 设定在有输入时不能切换至英文状态
      # 注意！！需要关闭fxcit的shift切换输入法快捷键
      Shift_L: commit_code
      Shift_R: commit_code #


init-rime.el

(use-package rime
  :bind
  (
   :map
   rime-active-mode
   ("M-j" . 'rime-inline-ascii)
   :map rime-mode-map
   ("C-`" . 'rime-send-keybinding))

  :custom
  (
   (rime-posframe-properties
    (list :font "Sarasa UI SC-20"
          :internal-border-width 10))
   (default-input-method "rime")
   (rime-inline-ascii-trigger 'shift-l)
   (rime-show-candidate 'posframe)))





(setq rime-disable-predicates
        ;; 行首输入符号
      '(rime-predicate-punctuation-line-begin-p
        ;; 中文字符加空格之后输入符号
        rime-predicate-punctuation-after-space-cc-p
        ;; 中文字符加空格之后输入英文
        rime-predicate-space-after-cc-p
        ;; 英文使用半角符号
        rime-predicate-punctuation-after-ascii-p
        ;; 编程模式，只在注释中输入中文
        rime-predicate-prog-in-code-p))

   
(provide 'init-rime)

**Comment by cnsunyour** [comment]
emacs 无法捕获单独 shift 键，这里设置的 `rime-inline-ascii-trigger` 仅仅是为自动切换 Inline 模式而用。
