### ISSUE TITLE
[Feature] 使用方向键选择候选

### ISSUE THREAD

**Issue by toure00** [DogLooksGood/emacs-rime#95]
**问题描述**

狗哥好，hhkb和其他一些自带方向键快捷键的键盘，用户会比较习惯使用方向键，希望能够使用方向键来选择候选。

**Comment by cnsunyour** [comment]
加为 bug 标记不太好吧？

**Comment by cnsunyour** [comment]
另外恕我孤陋寡闻，我插嘴问一句，用方向键选择候选词的用户多吗？我还是头一次听说有用方向键选词的。

**Comment by toure00** [comment]
> 加为 bug 标记不太好吧？

这个标记是默认加的，我不知道在哪改，看标题你应该可以知道我的意思不是 [BUG] ，而是 ［Feature］。
> 另外恕我孤陋寡闻，我插嘴问一句，用方向键选择候选词的用户多吗？我还是头一次听说有用方向键选词的。 

至于用方向键选词，我的意思是一些键盘，比如hhkb就没有方向键，他的方向键是组合键，我想大家还是用的习惯的，mac自带的输入法也是用方向键选词，而不是 C-n C-p，mac上的rime输入法鼠须管同样也支持方向键选词，当然你喜欢的话也可以用 C-n C-p。

**Comment by toure00** [comment]
当然我也只是提一下，狗哥要是觉得没必要，那我就关了这个 issue

**Comment by cnsunyour** [comment]
噢噢，请不要误会，我是刚好看到这个 issue ，顺嘴问一下下。

**Comment by DogLooksGood** [comment]
dd3d95388bdc77c465490f95f9daa5b8df166f1f

可以测试一下。

**Comment by toure00** [comment]
可以的，感谢狗哥
