### ISSUE TITLE
rime-predicate-prog-in-code-p 光标是字符串内的判断似乎有问题。

### ISSUE THREAD

**Issue by jixiuf** [DogLooksGood/emacs-rime#99]
**问题描述**
感觉 ` rime-predicate-prog-in-code-p ` 应该改成下面这样
原函数，当光标在字符串内时，无法启用中文输入
比如
```
（setq str "this is a光标在这里 string")
```
```

(defun rime-predicate-prog-in-code-p ()
  "If cursor is in code.

Can be used in `rime-disable-predicates' and `rime-inline-predicates'."
  (and (derived-mode-p 'prog-mode 'conf-mode )
       (not (nth 3 (syntax-ppss)))      ;not in string
       (not (nth 4 (syntax-ppss)))))    ;not in comment
```
简明的问题描述

**Emacs中的配置**

```
(setq default-input-method "rime")
(setq rime-show-candidate 'posframe)
(setq rime-disable-predicates
      '(rime-predicate-evil-mode-p
        rime-predicate-prog-in-code-p
        ;; rime-predicate-after-alphabet-char-p
        ;; rime-predicate-auto-english-p
        ))
(require 'rime)

```

 

**是否可在 emacs -Q 中复现**

是

**截图**

展示错误的截图或动图

**环境信息**

- 操作系统：如macos
- Emacs版本：如 GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 

- Librime版本：如 1.5.3
- Librime安装方式： 手工编译
- 安装方式：Git

**Comment by DogLooksGood** [comment]
不好意思，有点不太理解。这个问题是指在字符串中这个断言应该返回 nil ，继而是保持在输入中文的状态吗？

按照目前的实现，现在这个断言应该就是这样的逻辑。

![image](https://user-images.githubusercontent.com/11796018/85668351-36bdbf80-b6f1-11ea-9ea1-a69645028a8d.png)

（因为我用的不是 evil ，所以断言有点区别，不过实际效果应该是相同的。）

**Comment by cnsunyour** [comment]
我也在 .el 文件中测试了一下，逻辑好像也没有问题，可以正常输入中文。

**Comment by jixiuf** [comment]
是我的问题， 确实，上面的逻辑是正常的。
```
(setq rime-disable-predicates
      '(rime-predicate-evil-mode-p
        rime-predicate-prog-in-code-p
        rime-predicate-auto-english-p
        ))
```
但当我把`rime-predicate-auto-english-p` 加入进去的时候， "光标" 在""中的时候就没法输入中文了
不过我的改动似乎也没解决这个问题。 引号中先输入一个空格似乎就可以输入中文了

**Comment by cnsunyour** [comment]
因为 `rime-predicate-auto-english-p` 的作用就是在英文字符后面继续输入英文，空格切换中英文。直接在 “” 里因为紧临引号，所以输入的是英文，如果这时需要输入中文，应当使用强制中文输入函数 `rime-force-enable` 来实现

**Comment by DogLooksGood** [comment]
可以试试这样的组合

```
(setq rime-disable-predicates '(rime-predicate-evil-mode-p
                              rime-predicate-prog-in-code-p
                              rime-predicate-after-alphabet-char-p))
(setq rime-inline-predicates '(rime-predicate-space-after-cc-p))
```

这样的话是，代码中，英文字符后面是关闭的。然后 中文接空格的后面是 inline
